import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { ProductServiceV37G3A } from "../src/v37/product-service-v37g3a.ts";
import { digestObject, stableJson } from "../src/hash.ts";
import { PROJECT_ROOT } from "./helpers.ts";

const actions=["run_primary","run_recovery","confirm_recovery_evidence","request_recovery_admission","produce_candidate","run_regression","run_follow_up","confirm_follow_up_evidence","request_follow_up_admission","assess_state"] as const;
let serial=0;function service(pass=true){return new ProductServiceV37G3A(PROJECT_ROOT,{regressionCandidatePass:pass,mintId:(kind)=>`v37-g3a-test-${kind}-${++serial}`,now:(()=>{let n=0;return()=>new Date(Date.UTC(2026,7,20,16,0,n++)).toISOString()})()});}
test.before(()=>{for(const path of [".runs/v37/g3a-product",".runs/v37/g3a/state-stores",".runs/v37/host-authority/v37-g3a-host-registry-v1"])rmSync(resolve(PROJECT_ROOT,path),{recursive:true,force:true});});

test("genuine comparator negative route terminates honestly",async()=>{const s=service(false);let m=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions.slice(0,6))m=await s.act(m.workflow_id,action);assert.equal(m.stage,"candidate_rejected");assert.deepEqual(m.available_actions,[]);});

test("production actions complete recovery, promotion, bound follow-up and retain assessment",async()=>{const s=service();let m=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)m=await s.act(m.workflow_id,action);assert.equal(m.stage,"complete");assert.equal(m.receipt_count,10);assert.ok(m.artifacts.some((item)=>item.kind==="state_assessment"));const reopened=service().getWorkflow(m.workflow_id);assert.deepEqual(reopened,m);});

test("Primary PASS stops with no recovery or learning availability",async()=>{const s=service();let m=await s.createWorkflow("v37-det-primary-pass");m=await s.act(m.workflow_id,"run_primary");assert.equal(m.stage,"no_recovery_needed");assert.deepEqual(m.available_actions,[]);assert.equal(m.artifacts.some((item)=>/recovery|candidate|state/.test(item.kind)),false);await assert.rejects(s.act(m.workflow_id,"run_recovery"),/premature|repeated/);});

test("multiple workflows remain isolated and receipt or formal artifact tamper fails reopen",async()=>{const s=service();const a=await s.createWorkflow("v37-det-recovery-promote-retain"),b=await s.createWorkflow("v37-det-recovery-promote-retain");assert.notEqual(a.workflow_id,b.workflow_id);const advanced=await s.act(a.workflow_id,"run_primary");assert.equal(advanced.stage,"ready_for_recovery");assert.equal(s.getWorkflow(b.workflow_id).stage,"ready_for_primary");const path=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",a.workflow_id,"journal/receipts/0001.json");const bytes=readFileSync(path,"utf8");const value=JSON.parse(bytes);value.workflow_id=b.workflow_id;writeFileSync(path,JSON.stringify(value));assert.throws(()=>s.getWorkflow(a.workflow_id),/canonical|chain|identity/);writeFileSync(path,bytes);const terminalPath=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",a.workflow_id,"primary/terminal.json"),terminalBytes=readFileSync(terminalPath,"utf8"),terminal=JSON.parse(terminalBytes);terminal.outcome="forged";writeFileSync(terminalPath,`${stableJson(terminal)}\n`);assert.throws(()=>s.getWorkflow(a.workflow_id),/formal artifact reference drift/);writeFileSync(terminalPath,terminalBytes);assert.equal(s.getWorkflow(a.workflow_id).stage,"ready_for_recovery");assert.equal(existsSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",b.workflow_id,"candidate.json")),false);});

test("disabled registration preserves accepted historical artifacts but makes workflow read-only",async()=>{
	const s=service();const created=await s.createWorkflow("v37-det-recovery-promote-retain");const registryPath=resolve(PROJECT_ROOT,"workbench/config/v37/g3a/registered-cases/registry-v1.json"),registryBytes=readFileSync(registryPath,"utf8"),registry=JSON.parse(registryBytes),entry=registry.entries.find((item:any)=>item.case_id==="v37-det-recovery-promote-retain");
	const disabledBody={schema_version:1,kind:"v37_case_registration_envelope",case_id:entry.case_id,manifest_version:entry.manifest_version,approved_manifest_body_digest:entry.manifest_body_digest,registration_revision:2,previous_registration_digest:entry.current_registration_digest,registration_status:"disabled",approval_record_id:"v37-g3a-main-registration-recovery-disabled-r2",approval_policy_id:"v37-main-reviewed-case-registration-v1",approved_at:"2026-08-20T17:00:00.000Z",disabled_at:"2026-08-20T17:00:01.000Z"};const disabled={...disabledBody,registration_digest:digestObject(disabledBody)},relative=".runs/v37/g3a-product/disabled/v37-det-recovery-r2.json",path=resolve(PROJECT_ROOT,relative);mkdirSync(resolve(path,".."),{recursive:true});writeFileSync(path,`${stableJson(disabled)}\n`);
	try{entry.envelope_locations.push(relative);entry.envelope_digests.push(disabled.registration_digest);entry.current_registration_digest=disabled.registration_digest;const {registry_index_digest:_old,...body}=registry;registry.registry_index_digest=digestObject(body);writeFileSync(registryPath,`${stableJson(registry)}\n`);const reopened=s.getWorkflow(created.workflow_id);assert.equal(reopened.historical_read_only,true);assert.deepEqual(reopened.available_actions,[]);assert.deepEqual(reopened.artifacts,created.artifacts);await assert.rejects(s.act(created.workflow_id,"run_primary"),/read-only/);}finally{writeFileSync(registryPath,registryBytes);rmSync(path,{force:true});}
});
