import assert from "node:assert/strict";
import { cpSync, existsSync, linkSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { ProductServiceV37G3A, type ProductPrimaryExecutionPortV37G3A } from "../src/v37/product-service-v37g3a.ts";
import { digestObject, fileSha256, stableJson, treeDigest } from "../src/hash.ts";
import { PROJECT_ROOT } from "./helpers.ts";

const actions=["run_primary","run_recovery","confirm_recovery_evidence","request_recovery_admission","produce_candidate","run_regression","run_follow_up","confirm_follow_up_evidence","request_follow_up_admission","assess_state"] as const;
let serial=0;function service(pass=true){return new ProductServiceV37G3A(PROJECT_ROOT,{regressionCandidatePass:pass,mintId:(kind)=>`v37-g3a-test-${kind}-${++serial}`,now:(()=>{let n=0;return()=>new Date(Date.UTC(2026,7,20,16,0,n++)).toISOString()})()});}
function jsonInventory(roots:string[]):Record<string,string>{const result:Record<string,string>={};const visit=(path:string)=>{if(!existsSync(path))return;const stats=lstatSync(path);if(stats.isDirectory()){for(const name of readdirSync(path).sort())visit(resolve(path,name));}else if(stats.isFile()&&path.endsWith(".json"))result[path]=readFileSync(path,"utf8");};for(const root of roots)visit(root);return result;}
test.before(()=>{for(const path of [".runs/v37/g3a-product",".runs/v37/g3a/state-stores",".runs/v37/host-authority/v37-g3a-host-registry-v1"])rmSync(resolve(PROJECT_ROOT,path),{recursive:true,force:true});});

test("genuine comparator negative route terminates honestly",async()=>{const s=service(false);let m=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions.slice(0,6))m=await s.act(m.workflow_id,action);assert.equal(m.stage,"candidate_rejected");assert.deepEqual(m.available_actions,[]);});

test("two sequential workflows survive later State promotion and restart",async()=>{const s=service();let first=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)first=await s.act(first.workflow_id,action);let second=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)second=await s.act(second.workflow_id,action);for(const model of [first,second]){assert.equal(model.stage,"complete");assert.equal(model.receipt_count,10);assert.ok(model.artifacts.some((item)=>item.kind==="state_version"));assert.ok(model.artifacts.some((item)=>item.kind==="state_assessment"));}const restarted=service();assert.deepEqual(restarted.getWorkflow(first.workflow_id),first);assert.deepEqual(restarted.getWorkflow(second.workflow_id),second);});

test("Primary PASS stops with no recovery or learning availability",async()=>{const s=service();let m=await s.createWorkflow("v37-det-primary-pass");m=await s.act(m.workflow_id,"run_primary");assert.equal(m.stage,"no_recovery_needed");assert.deepEqual(m.available_actions,[]);assert.equal(m.artifacts.some((item)=>/recovery|candidate|state/.test(item.kind)),false);await assert.rejects(s.act(m.workflow_id,"run_recovery"),/premature|repeated/);});

test("production workflow identities do not collide across service restarts",async()=>{const first=await new ProductServiceV37G3A(PROJECT_ROOT).createWorkflow("v37-det-primary-pass"),second=await new ProductServiceV37G3A(PROJECT_ROOT).createWorkflow("v37-det-primary-pass");assert.notEqual(first.workflow_id,second.workflow_id);assert.match(first.workflow_id,/^v37-g3a-workflow-[0-9a-f-]{36}$/);assert.match(second.workflow_id,/^v37-g3a-workflow-[0-9a-f-]{36}$/);});

test("a later real-declared Case requires matching Host construction authority and accepts only formal simulated observations",async()=>{
	const caseId="v37-real-third-host-port",configRoot=resolve(PROJECT_ROOT,".runs/v37/g3a-product/third-config"),manifestRelative=".runs/v37/g3a-product/third-config/manifest.json",envelopeRelative=".runs/v37/g3a-product/third-config/envelope.json",profileRelative=".runs/v37/g3a-product/third-config/profile.json",registryPath=resolve(PROJECT_ROOT,"workbench/config/v37/g3a/registered-cases/registry-v1.json"),registryBytes=readFileSync(registryPath,"utf8"),registry=JSON.parse(registryBytes);
	const primaryAccess={credential_reads:1,network_calls:2,external_provider_calls:1,real_model_calls:1},followUpAccess={credential_reads:1,network_calls:1,external_provider_calls:1,real_model_calls:1};
	const sourceEntry=registry.entries.find((item:any)=>item.case_id==="v37-det-primary-pass"),manifest=JSON.parse(readFileSync(resolve(PROJECT_ROOT,sourceEntry.manifest_location),"utf8")),profile=JSON.parse(readFileSync(resolve(PROJECT_ROOT,sourceEntry.follow_up_execution_profile_location),"utf8"));
	manifest.case_id=caseId;manifest.provider_profile_spec={spec_id:"v37-g3a-real-simulated-primary-v1",body:{provider_id:"host-registered-simulated",model_id:"host/simulated",primary_mode:"pass",candidate_modes:[],real_access:true,execution_port_kind:"injected",access_expectation:primaryAccess}};manifest.provider_profile_spec.spec_digest=digestObject(manifest.provider_profile_spec.body);const {manifest_body_digest:_manifestDigest,...manifestBody}=manifest;manifest.manifest_body_digest=digestObject(manifestBody);
	profile.case_id=caseId;profile.manifest_body_digest=manifest.manifest_body_digest;profile.parent_provider_profile_digest=manifest.provider_profile_spec.spec_digest;profile.provider_profile={profile_id:"v37-g3a-real-simulated-follow-up-v1",provider_kind:"host_registered_external_v37g3a",model_id:"host/simulated",external:true,...followUpAccess};profile.provider_profile_digest=digestObject(profile.provider_profile);const {follow_up_execution_profile_digest:_profileDigest,...profileBody}=profile;profile.follow_up_execution_profile_digest=digestObject(profileBody);
	const envelopeBody={schema_version:1,kind:"v37_case_registration_envelope",case_id:caseId,manifest_version:1,approved_manifest_body_digest:manifest.manifest_body_digest,registration_revision:1,previous_registration_digest:null,registration_status:"accepted",approval_record_id:"v37-g3a-third-host-port-r1",approval_policy_id:"v37-main-reviewed-case-registration-v1",approved_at:"2026-08-20T18:40:00.000Z",disabled_at:null},envelope={...envelopeBody,registration_digest:digestObject(envelopeBody)};
	mkdirSync(configRoot,{recursive:true});writeFileSync(resolve(PROJECT_ROOT,manifestRelative),`${stableJson(manifest)}\n`);writeFileSync(resolve(PROJECT_ROOT,profileRelative),`${stableJson(profile)}\n`);writeFileSync(resolve(PROJECT_ROOT,envelopeRelative),`${stableJson(envelope)}\n`);registry.entries.push({case_id:caseId,manifest_version:1,manifest_location:manifestRelative,manifest_body_digest:manifest.manifest_body_digest,envelope_locations:[envelopeRelative],envelope_digests:[envelope.registration_digest],current_registration_digest:envelope.registration_digest,follow_up_execution_profile_location:profileRelative,follow_up_execution_profile_digest:profile.follow_up_execution_profile_digest});registry.entries.sort((a:any,b:any)=>a.case_id.localeCompare(b.case_id));const {registry_index_digest:_registryDigest,...registryBody}=registry;registry.registry_index_digest=digestObject(registryBody);writeFileSync(registryPath,`${stableJson(registry)}\n`);
	let credentialReads=0,networkCalls=0,providerCalls=0,modelCalls=0;
	const formalPrimary:ProductPrimaryExecutionPortV37G3A={execute:async({runId,runRoot,loadedCase})=>{const taskSpec=loadedCase.manifest.primary_task_spec.body as any,task=JSON.parse(readFileSync(resolve(PROJECT_ROOT,taskSpec.task_ref),"utf8")),workspace=resolve(runRoot,"primary/workspace");mkdirSync(resolve(workspace,".."),{recursive:true});cpSync(resolve(PROJECT_ROOT,task.workspace_source_ref),workspace,{recursive:true});const body={schema_version:1,kind:"v37_g3a_primary_terminal",run_id:runId,task_id:taskSpec.task_id,workspace_digest:treeDigest(workspace),verifier_source_sha256:(loadedCase.manifest.primary_verifier_spec.body as any).source_sha256,verifier_status:"passed",outcome:"passed",...primaryAccess},terminal={...body,terminal_digest:digestObject(body)};writeFileSync(resolve(runRoot,"terminal.json"),`${stableJson(terminal)}\n`);return terminal;}};
	const malformedPrimary:ProductPrimaryExecutionPortV37G3A={execute:async({runId,runRoot})=>{const body={schema_version:99,kind:"wrong",run_id:runId,outcome:"passed",verifier_status:"passed",...primaryAccess},terminal={...body,terminal_digest:digestObject(body)};mkdirSync(runRoot,{recursive:true});writeFileSync(resolve(runRoot,"terminal.json"),`${stableJson(terminal)}\n`);return terminal;}};
	const followUpRuntime={execute:async()=>{throw new Error("simulated Primary-pass Case must not dispatch follow-up Runtime");}};
	const authorization={case_id:caseId,manifest_body_digest:manifest.manifest_body_digest,follow_up_execution_profile_digest:profile.follow_up_execution_profile_digest,primary_access_expectation:primaryAccess,follow_up_access_expectation:followUpAccess};
	try{
		const configOnly=new ProductServiceV37G3A(PROJECT_ROOT);assert.equal(configOnly.listCases().find((item)=>item.case_id===caseId)?.available_for_new_workflow,false);await assert.rejects(configOnly.createWorkflow(caseId),/authority and ports/);
		const portsOnly=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:{primary:formalPrimary,followUpRuntime}}});assert.equal(portsOnly.listCases().find((item)=>item.case_id===caseId)?.available_for_new_workflow,false);await assert.rejects(portsOnly.createWorkflow(caseId),/authority and ports/);
		const malformed=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:{primary:malformedPrimary,followUpRuntime}},realAccessAuthorization:authorization,mintId:(kind)=>`v37-g3a-malformed-${kind}`});const malformedWorkflow=await malformed.createWorkflow(caseId);await assert.rejects(malformed.act(malformedWorkflow.workflow_id,"run_primary"),/exact-key|identity/);assert.equal(malformed.getWorkflow(malformedWorkflow.workflow_id).receipt_count,0);
		const s=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:{primary:formalPrimary,followUpRuntime}},realAccessAuthorization:authorization,mintId:(kind)=>`v37-g3a-third-${kind}`});assert.deepEqual(s.listCases().map((item)=>item.case_id),["v37-det-primary-pass","v37-det-recovery-promote-retain",caseId]);let model=await s.createWorkflow(caseId);model=await s.act(model.workflow_id,"run_primary");assert.equal(model.stage,"no_recovery_needed");assert.deepEqual(model.available_actions,[]);assert.deepEqual({credentialReads,networkCalls,providerCalls,modelCalls},{credentialReads:0,networkCalls:0,providerCalls:0,modelCalls:0});
	}finally{writeFileSync(registryPath,registryBytes);rmSync(configRoot,{recursive:true,force:true});}
});

test("frozen zero-access Cases reject injected execution-port and authorization overrides",()=>{
	const invalid:ProductPrimaryExecutionPortV37G3A={execute:async()=>({})};
	assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{"v37-det-primary-pass":{primary:invalid}}}),/cannot be overridden/);
	assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{realAccessAuthorization:{case_id:"v37-det-primary-pass",manifest_body_digest:"0".repeat(64),follow_up_execution_profile_digest:"0".repeat(64),primary_access_expectation:{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0},follow_up_access_expectation:{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0}}}),/does not match/);
});

test("Primary preflight rejects Task, instruction, Source and Verifier drift before dispatch",async()=>{
	const targets=[
		"workbench/fixtures/v37g3a/primary-pass/task.json",
		"workbench/fixtures/v37g3a/primary-pass/instruction.md",
		"workbench/fixtures/v37g3a/primary-pass/workspace/src/subject.ts",
		"fixtures/verifiers/v1/parse-duration.mjs",
	];
	for(const relativePath of targets){const s=service(),created=await s.createWorkflow("v37-det-primary-pass"),path=resolve(PROJECT_ROOT,relativePath),bytes=readFileSync(path,"utf8");try{writeFileSync(path,`${bytes}\n`);await assert.rejects(s.act(created.workflow_id,"run_primary"),/frozen Primary/);assert.equal(s.getWorkflow(created.workflow_id).stage,"ready_for_primary");assert.equal(existsSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id)),false);}finally{writeFileSync(path,bytes);}}
});

test("multiple workflows remain isolated and receipt or formal artifact tamper fails reopen",async()=>{const s=service();const a=await s.createWorkflow("v37-det-recovery-promote-retain"),b=await s.createWorkflow("v37-det-recovery-promote-retain");assert.notEqual(a.workflow_id,b.workflow_id);const advanced=await s.act(a.workflow_id,"run_primary");assert.equal(advanced.stage,"ready_for_recovery");assert.equal(s.getWorkflow(b.workflow_id).stage,"ready_for_primary");const path=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",a.workflow_id,"journal/receipts/0001.json");const bytes=readFileSync(path,"utf8");const value=JSON.parse(bytes);value.workflow_id=b.workflow_id;writeFileSync(path,JSON.stringify(value));assert.throws(()=>s.getWorkflow(a.workflow_id),/canonical|chain|identity/);writeFileSync(path,bytes);const terminalPath=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",a.workflow_id,"primary/terminal.json"),terminalBytes=readFileSync(terminalPath,"utf8"),terminal=JSON.parse(terminalBytes);terminal.outcome="forged";writeFileSync(terminalPath,`${stableJson(terminal)}\n`);assert.throws(()=>s.getWorkflow(a.workflow_id),/formal artifact reference drift/);writeFileSync(terminalPath,terminalBytes);assert.equal(s.getWorkflow(a.workflow_id).stage,"ready_for_recovery");assert.equal(existsSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",b.workflow_id,"candidate.json")),false);});

test("journal descendants reject junctions and formal artifacts reject hardlinks",async()=>{
	const s=service(),created=await s.createWorkflow("v37-det-primary-pass"),journalReceipts=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",created.workflow_id,"journal/receipts"),junctionTarget=resolve(PROJECT_ROOT,".runs/v37/g3a-product/junction-target",created.workflow_id);mkdirSync(junctionTarget,{recursive:true});symlinkSync(junctionTarget,journalReceipts,"junction");try{assert.throws(()=>s.getWorkflow(created.workflow_id),/link|reparse/);}finally{unlinkSync(journalReceipts);}
	const completed=await s.act(created.workflow_id,"run_primary"),terminal=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id,"primary/terminal.json"),hardlink=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id,"primary/terminal-hardlink.json");linkSync(terminal,hardlink);try{assert.throws(()=>s.getWorkflow(completed.workflow_id),/singly linked/);}finally{rmSync(hardlink,{force:true});}assert.equal(s.getWorkflow(completed.workflow_id).stage,"no_recovery_needed");
});

test("disabled registration preserves accepted historical artifacts but makes workflow read-only",async()=>{
	const s=service();let created=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)created=await s.act(created.workflow_id,action);const artifactSnapshot=structuredClone(created.artifacts),roots=[resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/regression",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/assessments",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a/state-stores/v37-det-recovery-promote-retain")],byteSnapshot=jsonInventory(roots);const registryPath=resolve(PROJECT_ROOT,"workbench/config/v37/g3a/registered-cases/registry-v1.json"),registryBytes=readFileSync(registryPath,"utf8"),registry=JSON.parse(registryBytes),entry=registry.entries.find((item:any)=>item.case_id==="v37-det-recovery-promote-retain");
	const disabledBody={schema_version:1,kind:"v37_case_registration_envelope",case_id:entry.case_id,manifest_version:entry.manifest_version,approved_manifest_body_digest:entry.manifest_body_digest,registration_revision:2,previous_registration_digest:entry.current_registration_digest,registration_status:"disabled",approval_record_id:"v37-g3a-main-registration-recovery-disabled-r2",approval_policy_id:"v37-main-reviewed-case-registration-v1",approved_at:"2026-08-20T17:00:00.000Z",disabled_at:"2026-08-20T17:00:01.000Z"};const disabled={...disabledBody,registration_digest:digestObject(disabledBody)},relative=".runs/v37/g3a-product/disabled/v37-det-recovery-r2.json",path=resolve(PROJECT_ROOT,relative);mkdirSync(resolve(path,".."),{recursive:true});writeFileSync(path,`${stableJson(disabled)}\n`);
	try{entry.envelope_locations.push(relative);entry.envelope_digests.push(disabled.registration_digest);entry.current_registration_digest=disabled.registration_digest;const {registry_index_digest:_old,...body}=registry;registry.registry_index_digest=digestObject(body);writeFileSync(registryPath,`${stableJson(registry)}\n`);const reopened=service().getWorkflow(created.workflow_id);assert.equal(reopened.stage,"complete");assert.equal(reopened.historical_read_only,true);assert.deepEqual(reopened.available_actions,[]);assert.deepEqual(reopened.artifacts,artifactSnapshot);assert.deepEqual(jsonInventory(roots),byteSnapshot);for(const action of actions)await assert.rejects(s.act(created.workflow_id,action),/read-only/);assert.deepEqual(jsonInventory(roots),byteSnapshot);}finally{writeFileSync(registryPath,registryBytes);rmSync(path,{force:true});}
});
