import assert from "node:assert/strict";
import { cpSync, existsSync, linkSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { ProductServiceV37G3A, type ProductCaseExecutionPortsV37G3A, type ProductPrimaryExecutionPortV37G3A, type ProductRealAccessAuthorizationV37G3A } from "../src/v37/product-service-v37g3a.ts";
import { digestObject, stableJson, treeDigest } from "../src/hash.ts";
import { createDeterministicExecutionPortV2A, executeRunV2A } from "../src/run-v2.ts";
import { deterministicFauxFollowUpRuntimePortV37G3A } from "../src/v37/registered-follow-up-v37g3a.ts";
import { constructionAuthorityDigestsV37G3A } from "../src/v37/host-registry-v37g3a.ts";
import { PROJECT_ROOT } from "./helpers.ts";

const actions=["run_primary","run_recovery","confirm_recovery_evidence","request_recovery_admission","produce_candidate","run_regression","run_follow_up","confirm_follow_up_evidence","request_follow_up_admission","assess_state"] as const;
let serial=0;function service(pass=true){return new ProductServiceV37G3A(PROJECT_ROOT,{regressionCandidatePass:pass,mintId:(kind)=>`v37-g3a-test-${kind}-${++serial}`,now:(()=>{let n=0;return()=>new Date(Date.UTC(2026,7,20,16,0,n++)).toISOString()})()});}
function jsonInventory(roots:string[]):Record<string,string>{const result:Record<string,string>={};const visit=(path:string)=>{if(!existsSync(path))return;const stats=lstatSync(path);if(stats.isDirectory()){for(const name of readdirSync(path).sort())visit(resolve(path,name));}else if(stats.isFile()&&path.endsWith(".json"))result[path]=readFileSync(path,"utf8");};for(const root of roots)visit(root);return result;}
test.before(()=>{for(const path of [".runs/v37/g3a-product",".runs/v37/g3a/state-stores",".runs/v37/host-authority/v37-g3a-host-registry-v1"])rmSync(resolve(PROJECT_ROOT,path),{recursive:true,force:true});});

test("genuine comparator negative route terminates honestly",async()=>{const s=service(false);let m=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions.slice(0,6))m=await s.act(m.workflow_id,action);assert.equal(m.stage,"candidate_rejected");assert.deepEqual(m.available_actions,[]);});

test("two sequential workflows survive later State promotion and restart",async()=>{const s=service();let first=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)first=await s.act(first.workflow_id,action);let second=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)second=await s.act(second.workflow_id,action);for(const model of [first,second]){assert.equal(model.stage,"complete");assert.equal(model.receipt_count,10);assert.ok(model.artifacts.some((item)=>item.kind==="state_version"));assert.ok(model.artifacts.some((item)=>item.kind==="state_assessment"));}const restarted=service();assert.deepEqual(restarted.getWorkflow(first.workflow_id),first);assert.deepEqual(restarted.getWorkflow(second.workflow_id),second);});

test("Primary PASS stops with no recovery or learning availability",async()=>{const s=service();let m=await s.createWorkflow("v37-det-primary-pass");m=await s.act(m.workflow_id,"run_primary");assert.equal(m.stage,"no_recovery_needed");assert.deepEqual(m.available_actions,[]);assert.equal(m.artifacts.some((item)=>/recovery|candidate|state/.test(item.kind)),false);await assert.rejects(s.act(m.workflow_id,"run_recovery"),/premature|repeated/);});

test("production workflow identities do not collide across service restarts",async()=>{const first=await new ProductServiceV37G3A(PROJECT_ROOT).createWorkflow("v37-det-primary-pass"),second=await new ProductServiceV37G3A(PROJECT_ROOT).createWorkflow("v37-det-primary-pass");assert.notEqual(first.workflow_id,second.workflow_id);assert.match(first.workflow_id,/^v37-g3a-workflow-[0-9a-f-]{36}$/);assert.match(second.workflow_id,/^v37-g3a-workflow-[0-9a-f-]{36}$/);});

type AccessCounters={credential_reads:number;network_calls:number;external_provider_calls:number;real_model_calls:number};
function realCounters(providerDispatches:number):AccessCounters{return {credential_reads:1,network_calls:providerDispatches,external_provider_calls:providerDispatches,real_model_calls:providerDispatches};}
function accessMaxima(actual:AccessCounters):AccessCounters{return {credential_reads:actual.credential_reads+1,network_calls:actual.network_calls+1,external_provider_calls:actual.external_provider_calls+1,real_model_calls:actual.real_model_calls+1};}
function primaryDispatches(primaryMode:"pass"|"fail",candidateModes:readonly ["pass"|"fail","pass"|"fail"]):number{return primaryMode==="pass"?3:1+candidateModes.reduce((total,mode)=>total+(mode==="pass"?3:1),0);}
type LocalMockFamily="primary"|"candidate_proposal"|"regression_validation"|"follow_up_runtime";
type ActualExternalOperation="credential_reads"|"network_calls"|"external_provider_calls"|"real_model_calls";
function createActualOperationTracker(){
	const local_mock_invocations:Record<LocalMockFamily,number>={primary:0,candidate_proposal:0,regression_validation:0,follow_up_runtime:0},actual_external_operations:Record<ActualExternalOperation,number>={credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0};
	return {local_mock_invocations,actual_external_operations,recordLocalMock:(family:LocalMockFamily)=>{local_mock_invocations[family]+=1;},recordActualExternalOperation:(operation:ActualExternalOperation)=>{actual_external_operations[operation]+=1;}};
}
type ActualOperationTracker=ReturnType<typeof createActualOperationTracker>;
async function withTemporaryRealCase(options:{primaryMode:"pass"|"fail";candidateModes:readonly ["pass"|"fail","pass"|"fail"];executionPortKind?:"injected"|"internal_deterministic";primaryActual?:AccessCounters;primaryMaxima?:AccessCounters;followActual?:AccessCounters;followMaxima?:AccessCounters},run:(value:{caseId:string;manifest:any;profile:any;authorization:ProductRealAccessAuthorizationV37G3A;ports:ProductCaseExecutionPortsV37G3A;tracker:ActualOperationTracker;primaryActual:AccessCounters;primaryMaxima:AccessCounters;followActual:AccessCounters;followMaxima:AccessCounters})=>Promise<void>){
	const caseId=`v37-real-${options.primaryMode}-${options.candidateModes.join("-")}`,configRoot=resolve(PROJECT_ROOT,".runs/v37/g3a-product/third-config"),manifestRelative=".runs/v37/g3a-product/third-config/manifest.json",envelopeRelative=".runs/v37/g3a-product/third-config/envelope.json",profileRelative=".runs/v37/g3a-product/third-config/profile.json",registryPath=resolve(PROJECT_ROOT,"workbench/config/v37/g3a/registered-cases/registry-v1.json"),registryBytes=readFileSync(registryPath,"utf8"),registry=JSON.parse(registryBytes),sourceEntry=registry.entries.find((item:any)=>item.case_id==="v37-det-recovery-promote-retain"),manifest=JSON.parse(readFileSync(resolve(PROJECT_ROOT,sourceEntry.manifest_location),"utf8")),profile=JSON.parse(readFileSync(resolve(PROJECT_ROOT,sourceEntry.follow_up_execution_profile_location),"utf8"));
	const primaryActual=options.primaryActual??realCounters(primaryDispatches(options.primaryMode,options.candidateModes)),primaryMaxima=options.primaryMaxima??accessMaxima(primaryActual),followActual=options.followActual??realCounters(2),followMaxima=options.followMaxima??accessMaxima(followActual);
	manifest.case_id=caseId;manifest.provider_profile_spec={spec_id:"v37-g3a-real-simulated-primary-v1",body:{provider_id:"host-registered-simulated",model_id:"host/simulated",primary_mode:options.primaryMode,candidate_modes:options.candidateModes,real_access:true,execution_port_kind:options.executionPortKind??"injected",access_expectation:primaryMaxima}};manifest.provider_profile_spec.spec_digest=digestObject(manifest.provider_profile_spec.body);const {manifest_body_digest:_manifestDigest,...manifestBody}=manifest;manifest.manifest_body_digest=digestObject(manifestBody);profile.case_id=caseId;profile.manifest_body_digest=manifest.manifest_body_digest;profile.parent_provider_profile_digest=manifest.provider_profile_spec.spec_digest;profile.provider_profile={profile_id:"v37-g3a-real-simulated-follow-up-v1",provider_kind:"host_registered_external_v37g3a",model_id:"host/simulated",external:true,...followMaxima};profile.provider_profile_digest=digestObject(profile.provider_profile);const {follow_up_execution_profile_digest:_profileDigest,...profileBody}=profile;profile.follow_up_execution_profile_digest=digestObject(profileBody);const envelopeBody={schema_version:1,kind:"v37_case_registration_envelope",case_id:caseId,manifest_version:1,approved_manifest_body_digest:manifest.manifest_body_digest,registration_revision:1,previous_registration_digest:null,registration_status:"accepted",approval_record_id:"v37-g3a-real-simulated-r1",approval_policy_id:"v37-main-reviewed-case-registration-v1",approved_at:"2026-08-20T18:40:00.000Z",disabled_at:null},envelope={...envelopeBody,registration_digest:digestObject(envelopeBody)};mkdirSync(configRoot,{recursive:true});writeFileSync(resolve(PROJECT_ROOT,manifestRelative),`${stableJson(manifest)}\n`);writeFileSync(resolve(PROJECT_ROOT,profileRelative),`${stableJson(profile)}\n`);writeFileSync(resolve(PROJECT_ROOT,envelopeRelative),`${stableJson(envelope)}\n`);registry.entries.push({case_id:caseId,manifest_version:1,manifest_location:manifestRelative,manifest_body_digest:manifest.manifest_body_digest,envelope_locations:[envelopeRelative],envelope_digests:[envelope.registration_digest],current_registration_digest:envelope.registration_digest,follow_up_execution_profile_location:profileRelative,follow_up_execution_profile_digest:profile.follow_up_execution_profile_digest});registry.entries.sort((a:any,b:any)=>a.case_id.localeCompare(b.case_id));const {registry_index_digest:_registryDigest,...registryBody}=registry;registry.registry_index_digest=digestObject(registryBody);writeFileSync(registryPath,`${stableJson(registry)}\n`);
	const tracker=createActualOperationTracker();const primary:ProductPrimaryExecutionPortV37G3A={execute:async({runId,runRoot})=>{tracker.recordLocalMock("primary");return executeRunV2A({projectRoot:PROJECT_ROOT,runRoot,runId,primaryMode:options.primaryMode,candidateModes:options.candidateModes,executionPort:createDeterministicExecutionPortV2A(),realExecutionAuthorized:true,realCallCounters:primaryActual}) as unknown as Record<string,unknown>;}};const candidateProposal={propose:async(input:any)=>{tracker.recordLocalMock("candidate_proposal");return {schema_version:1,proposal_id:`real-sim-${input.opportunity.evidence_identity.evidence_digest.slice(0,20)}`,evidence_digest:input.opportunity.evidence_identity.evidence_digest,expected_base_state_digest:input.expected_base_state_digest,diagnosis:{pattern_id:input.opportunity.trigger,statement:"The registered Primary failed before bounded Recovery succeeded.",evidence_refs:structuredClone(input.opportunity.evidence_refs)},lesson:{statement:"Use the registered verification discipline.",expected_outcome:"The related task is checked before completion.",applicability:{task_kinds:["typescript-maintenance"],failure_families:["verifier-failure"]}},edits:[{kind:"prompt_addendum",entry_id:"v37-verify-before-finish",content:"Before reporting completion, run the task-declared check and rely on its result rather than self-assessment.",applicability:{task_kinds:["typescript-maintenance"],failure_families:["verifier-failure"]}}]};}};const regressionValidation={execute:async({state,workspaceRoot}:any)=>{tracker.recordLocalMock("regression_validation");if(state.status==="staged_inactive")writeFileSync(resolve(workspaceRoot,"subject.txt"),"fixed\n");return {settled:true as const,events:[{seq:1,type:"provider_call" as const,call_id:`sim-${state.status}`} ]};}};const followUpRuntime={execute:async(request:any)=>{tracker.recordLocalMock("follow_up_runtime");const result=await deterministicFauxFollowUpRuntimePortV37G3A.execute(request),path=resolve(request.runtimeRoot,"runs",request.runId,"manifest.json"),manifestValue=JSON.parse(readFileSync(path,"utf8"));Object.assign(manifestValue,followActual);const {manifest_digest:_digest,...body}=manifestValue;manifestValue.manifest_digest=digestObject(body);writeFileSync(path,`${stableJson(manifestValue)}\n`);return {...result,manifest:manifestValue};}};const ports={primary,candidateProposal,regressionValidation,followUpRuntime},authorityDigests=constructionAuthorityDigestsV37G3A(manifest),authorization={case_id:caseId,manifest_body_digest:manifest.manifest_body_digest,follow_up_execution_profile_digest:profile.follow_up_execution_profile_digest,primary_access_expectation:primaryMaxima,follow_up_access_expectation:followMaxima,candidate_proposal_authority_digest:authorityDigests.candidateProposalAuthorityDigest,regression_authority_digest:authorityDigests.regressionAuthorityDigest};
	try{await run({caseId,manifest,profile,authorization,ports,tracker,primaryActual,primaryMaxima,followActual,followMaxima});}finally{writeFileSync(registryPath,registryBytes);rmSync(configRoot,{recursive:true,force:true});}
}

test("G3B counter maxima: under-cap and at-cap real usage completes Recovery and reopens",async()=>{
	const primaryActual=realCounters(7),followActual=realCounters(2);
	for(const atCap of [false,true])await withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"],primaryActual,primaryMaxima:atCap?primaryActual:accessMaxima(primaryActual),followActual,followMaxima:atCap?followActual:accessMaxima(followActual)},async({caseId,authorization,ports,tracker})=>{
		const create=()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-max-pass-${++serial}-${kind}`});
		let product=create(),model=await product.createWorkflow(caseId);
		for(const action of actions)model=await product.act(model.workflow_id,action);
		assert.equal(model.stage,"complete");assert.equal(model.receipt_count,10);assert.equal(create().getWorkflow(model.workflow_id).stage,"complete");
		assert.deepEqual(tracker.actual_external_operations,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});
	});
});

test("G3B counter maxima: Primary over-cap, ledger mismatch and zero actual fail without receipt or fallback",async()=>{
	const ledger=realCounters(7),zero={credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0};
	for(const [primaryActual,primaryMaxima] of [[ledger,{...accessMaxima(ledger),network_calls:6}],[{...ledger,network_calls:6,external_provider_calls:6,real_model_calls:6},accessMaxima(ledger)],[zero,accessMaxima(ledger)]] as const)await withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"],primaryActual,primaryMaxima},async({caseId,authorization,ports,tracker})=>{
		const product=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-max-primary-fail-${++serial}-${kind}`}),created=await product.createWorkflow(caseId);
		await assert.rejects(product.act(created.workflow_id,"run_primary"),/maximum|dispatch ledger|positive Credential/);
		const reopened=product.getWorkflow(created.workflow_id);assert.equal(reopened.stage,"ready_for_primary");assert.equal(reopened.receipt_count,0);assert.deepEqual(tracker.local_mock_invocations,{primary:1,candidate_proposal:0,regression_validation:0,follow_up_runtime:0});assert.deepEqual(tracker.actual_external_operations,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});
	});
});

test("G3B counter maxima: follow-up over-cap, request mismatch and zero actual fail without receipt or admission",async()=>{
	const aligned=realCounters(2),zero={credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0};
	for(const [followActual,followMaxima] of [[{...aligned,network_calls:3,external_provider_calls:3,real_model_calls:3},{credential_reads:2,network_calls:2,external_provider_calls:2,real_model_calls:2}],[realCounters(1),accessMaxima(aligned)],[zero,accessMaxima(aligned)]] as const)await withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"],followActual,followMaxima},async({caseId,authorization,ports,tracker})=>{
		const product=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-max-follow-fail-${++serial}-${kind}`});let model=await product.createWorkflow(caseId);
		for(const action of actions.slice(0,6))model=await product.act(model.workflow_id,action);
		assert.equal(model.stage,"ready_for_follow_up");const before=model.receipt_count;await assert.rejects(product.act(model.workflow_id,"run_follow_up"),/maximum|Provider requests|positive Credential/);
		model=product.getWorkflow(model.workflow_id);assert.equal(model.stage,"ready_for_follow_up");assert.equal(model.receipt_count,before);assert.equal(model.artifacts.some((item)=>item.kind==="follow_up_evidence"||item.kind==="follow_up_admission"),false);assert.equal(tracker.local_mock_invocations.follow_up_runtime,1);assert.deepEqual(tracker.actual_external_operations,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});
	});
});

test("G3B counter maxima: deterministic zero-access Recovery route remains exact and unchanged",async()=>{
	const product=service(),created=await product.createWorkflow("v37-det-recovery-promote-retain");let model=created;for(const action of actions)model=await product.act(model.workflow_id,action);assert.equal(model.stage,"complete");
	const primary=JSON.parse(readFileSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",model.workflow_id,"primary/terminal.json"),"utf8")),followRoot=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",model.workflow_id,"follow-up"),binding=JSON.parse(readFileSync(resolve(followRoot,"binding.json"),"utf8")),follow=JSON.parse(readFileSync(resolve(followRoot,"runtime/runs",binding.follow_up_run_id,"manifest.json"),"utf8"));
	assert.deepEqual(primary.real_call_counters,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});assert.deepEqual({credential_reads:follow.credential_reads,network_calls:follow.network_calls,external_provider_calls:follow.external_provider_calls,real_model_calls:follow.real_model_calls},{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});
});

test("real-declared V2 honest terminal matrix and authority negatives fail closed",async()=>{
	for(const [mode,candidates,stage] of [["pass",["pass","pass"],"no_recovery_needed"],["fail",["fail","fail"],"recovery_inconclusive"]] as const)await withTemporaryRealCase({primaryMode:mode,candidateModes:candidates},async({caseId,authorization,ports,primaryActual})=>{
		const configOnly=new ProductServiceV37G3A(PROJECT_ROOT);await assert.rejects(configOnly.createWorkflow(caseId),/authority and ports/);
		const portsOnly=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports}});await assert.rejects(portsOnly.createWorkflow(caseId),/authority and ports/);
		assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{realAccessAuthorization:authorization}),/requires exact/);
		for(const missing of ["primary","candidateProposal","regressionValidation","followUpRuntime"] as const){const incomplete={...ports};delete incomplete[missing];assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:incomplete as ProductCaseExecutionPortsV37G3A},realAccessAuthorization:authorization}),/requires exact/);}
		for(const key of ["manifest_body_digest","follow_up_execution_profile_digest","candidate_proposal_authority_digest","regression_authority_digest"] as const)assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:{...authorization,[key]:"0".repeat(64)}}),/does not match/);
		assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:{...authorization,case_id:"v37-real-foreign"}}),/does not identify/);assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:{...authorization,primary_access_expectation:{...authorization.primary_access_expectation,network_calls:99}}}),/does not match/);assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:{...authorization,follow_up_access_expectation:{...authorization.follow_up_access_expectation,network_calls:99}}}),/does not match/);
		const s=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-${kind}`});let model=await s.createWorkflow(caseId);model=await s.act(model.workflow_id,"run_primary");assert.equal(model.stage,stage);assert.deepEqual(model.available_actions,[]);assert.equal(model.receipt_count,1);
		if(mode==="pass"){
			const substituted:ProductPrimaryExecutionPortV37G3A={execute:async(request)=>{const terminal=await ports.primary.execute(request),path=resolve(request.runRoot,"terminal.json"),changed={...terminal,run_id:`${request.runId}-foreign`};writeFileSync(path,`${stableJson(changed)}\n`);return changed;}};const malformedService=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:{...ports,primary:substituted}},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-bad-${kind}`}),created=await malformedService.createWorkflow(caseId);await assert.rejects(malformedService.act(created.workflow_id,"run_primary"),/binding|inspection/);assert.equal(malformedService.getWorkflow(created.workflow_id).receipt_count,0);
			const localPass:ProductPrimaryExecutionPortV37G3A={execute:async(request)=>{const taskSpec=request.loadedCase.manifest.primary_task_spec.body as any,task=JSON.parse(readFileSync(resolve(PROJECT_ROOT,taskSpec.task_ref),"utf8")),workspace=resolve(request.runRoot,"primary/workspace");mkdirSync(resolve(workspace,".."),{recursive:true});cpSync(resolve(PROJECT_ROOT,task.workspace_source_ref),workspace,{recursive:true});const body={schema_version:1,kind:"v37_g3a_primary_terminal",run_id:request.runId,task_id:taskSpec.task_id,workspace_digest:treeDigest(workspace),verifier_source_sha256:(request.loadedCase.manifest.primary_verifier_spec.body as any).source_sha256,verifier_status:"passed",outcome:"passed",...primaryActual},terminal={...body,terminal_digest:digestObject(body)};writeFileSync(resolve(request.runRoot,"terminal.json"),`${stableJson(terminal)}\n`);return terminal;}};const localService=new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:{...ports,primary:localPass}},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-local-${kind}`}),localWorkflow=await localService.createWorkflow(caseId);await assert.rejects(localService.act(localWorkflow.workflow_id,"run_primary"),/must use an independently inspected V2 terminal/);assert.equal(localService.getWorkflow(localWorkflow.workflow_id).receipt_count,0);
		}
	});
	await withTemporaryRealCase({primaryMode:"pass",candidateModes:["pass","pass"],executionPortKind:"internal_deterministic"},async()=>{assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT),/real-access Primary provider profile invalid/);});
});

test("real-declared selected Recovery traverses the complete retained route and restart requires authority",async()=>withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"]},async({caseId,authorization,ports,tracker})=>{const create=()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-${kind}-${++serial}`}),portsOnly=()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{[caseId]:ports}});let service=create(),model=await service.createWorkflow(caseId);model=await service.act(model.workflow_id,"run_primary");assert.equal(model.stage,"ready_for_recovery");for(const action of actions.slice(1)){await assert.rejects(portsOnly().act(model.workflow_id,action),/construction authorization/);model=await service.act(model.workflow_id,action);}assert.equal(model.stage,"complete");assert.equal(model.receipt_count,10);service=create();assert.equal(service.getWorkflow(model.workflow_id).stage,"complete");assert.deepEqual(tracker.local_mock_invocations,{primary:1,candidate_proposal:1,regression_validation:2,follow_up_runtime:1});assert.equal(typeof tracker.recordActualExternalOperation,"function");assert.deepEqual(tracker.actual_external_operations,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});}));

test("real-declared Regression ignores the deterministic rejection switch and uses the supplied symmetric port",async()=>withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"]},async({caseId,authorization,ports,tracker})=>{const s=new ProductServiceV37G3A(PROJECT_ROOT,{regressionCandidatePass:false,caseExecutionPorts:{[caseId]:ports},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-switch-${kind}-${++serial}`});let model=await s.createWorkflow(caseId);for(const action of actions.slice(0,5))model=await s.act(model.workflow_id,action);model=await s.act(model.workflow_id,"run_regression");assert.equal(model.stage,"ready_for_follow_up");assert.equal(model.receipt_count,6);assert.equal(tracker.local_mock_invocations.regression_validation,2);assert.ok(model.artifacts.some((item)=>item.kind==="promotion_decision"));assert.equal(model.artifacts.some((item)=>item.kind==="regression_rejected"),false);}));

test("throwing real-declared Regression port produces no receipt and has no deterministic fallback",async()=>withTemporaryRealCase({primaryMode:"fail",candidateModes:["pass","pass"]},async({caseId,authorization,ports,tracker})=>{const throwingPorts:ProductCaseExecutionPortsV37G3A={...ports,regressionValidation:{execute:async()=>{tracker.recordLocalMock("regression_validation");throw new Error("supplied Regression port failed");}}},s=new ProductServiceV37G3A(PROJECT_ROOT,{regressionCandidatePass:false,caseExecutionPorts:{[caseId]:throwingPorts},realAccessAuthorization:authorization,mintId:(kind)=>`${caseId}-throw-${kind}-${++serial}`});let model=await s.createWorkflow(caseId);for(const action of actions.slice(0,5))model=await s.act(model.workflow_id,action);const before=model.receipt_count;await assert.rejects(s.act(model.workflow_id,"run_regression"),/supplied Regression port failed/);model=s.getWorkflow(model.workflow_id);assert.equal(tracker.local_mock_invocations.regression_validation,1);assert.equal(model.receipt_count,before);assert.equal(model.stage,"ready_for_regression");assert.equal(model.artifacts.some((item)=>item.kind==="regression_rejected"||item.kind==="promotion_decision"),false);assert.deepEqual(tracker.actual_external_operations,{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0});}));

test("frozen zero-access Cases reject injected execution-port and authorization overrides",()=>{
	const invalid:ProductPrimaryExecutionPortV37G3A={execute:async()=>({})};
	assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{caseExecutionPorts:{"v37-det-primary-pass":{primary:invalid}}}),/cannot be overridden/);
	assert.throws(()=>new ProductServiceV37G3A(PROJECT_ROOT,{realAccessAuthorization:{case_id:"v37-det-primary-pass",manifest_body_digest:"0".repeat(64),follow_up_execution_profile_digest:"0".repeat(64),primary_access_expectation:{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0},follow_up_access_expectation:{credential_reads:0,network_calls:0,external_provider_calls:0,real_model_calls:0},candidate_proposal_authority_digest:"0".repeat(64),regression_authority_digest:"0".repeat(64)}}),/does not match/);
});

test("Primary preflight rejects Task, instruction, Source and Verifier drift before dispatch",async()=>{
	const targets=[
		"workbench/fixtures/v37g3a/primary-pass/task.json",
		"workbench/fixtures/v37g3a/primary-pass/instruction.md",
		"workbench/fixtures/v37g3a/primary-pass/workspace/src/subject.ts",
		"fixtures/verifiers/v1/parse-duration.mjs",
	];
	for(const relativePath of targets){const s=service(),created=await s.createWorkflow("v37-det-primary-pass"),path=resolve(PROJECT_ROOT,relativePath),bytes=readFileSync(path,"utf8");try{writeFileSync(path,`${bytes}\n`);await assert.rejects(s.act(created.workflow_id,"run_primary"),/frozen Primary/);assert.equal(s.getWorkflow(created.workflow_id).stage,"ready_for_primary");assert.equal(existsSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id)),false);}finally{writeFileSync(path,bytes);}}
});

test("multiple workflows remain isolated and receipt or formal artifact tamper fails reopen",async()=>{const s=service();const a=await s.createWorkflow("v37-det-recovery-promote-retain"),b=await s.createWorkflow("v37-det-recovery-promote-retain");assert.notEqual(a.workflow_id,b.workflow_id);const advanced=await s.act(a.workflow_id,"run_primary");assert.equal(advanced.stage,"ready_for_recovery");assert.equal(s.getWorkflow(b.workflow_id).stage,"ready_for_primary");const path=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",a.workflow_id,"journal/receipts/0001.json");const bytes=readFileSync(path,"utf8");const value=JSON.parse(bytes);value.workflow_id=b.workflow_id;writeFileSync(path,JSON.stringify(value));assert.throws(()=>s.getWorkflow(a.workflow_id),/canonical|chain|identity/);writeFileSync(path,bytes);const terminalPath=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",a.workflow_id,"primary/terminal.json"),terminalBytes=readFileSync(terminalPath,"utf8"),terminal=JSON.parse(terminalBytes);terminal.outcome="forged";writeFileSync(terminalPath,`${stableJson(terminal)}\n`);assert.throws(()=>s.getWorkflow(a.workflow_id),/formal artifact reference drift/);writeFileSync(terminalPath,terminalBytes);assert.equal(s.getWorkflow(a.workflow_id).stage,"ready_for_recovery");assert.equal(existsSync(resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",b.workflow_id,"candidate.json")),false);});

test("journal descendants reject junctions and formal artifacts reject hardlinks",async()=>{
	const s=service(),created=await s.createWorkflow("v37-det-primary-pass"),journalReceipts=resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",created.workflow_id,"journal/receipts"),junctionTarget=resolve(PROJECT_ROOT,".runs/v37/g3a-product/junction-target",created.workflow_id);mkdirSync(junctionTarget,{recursive:true});symlinkSync(junctionTarget,journalReceipts,"junction");try{assert.throws(()=>s.getWorkflow(created.workflow_id),/link|reparse/);}finally{unlinkSync(journalReceipts);}
	const completed=await s.act(created.workflow_id,"run_primary"),terminal=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id,"primary/terminal.json"),hardlink=resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id,"primary/terminal-hardlink.json");linkSync(terminal,hardlink);try{assert.throws(()=>s.getWorkflow(completed.workflow_id),/singly linked/);}finally{rmSync(hardlink,{force:true});}assert.equal(s.getWorkflow(completed.workflow_id).stage,"no_recovery_needed");
});

test("disabled registration preserves accepted historical artifacts but makes workflow read-only",async()=>{
	const s=service();let created=await s.createWorkflow("v37-det-recovery-promote-retain");for(const action of actions)created=await s.act(created.workflow_id,action);const artifactSnapshot=structuredClone(created.artifacts),roots=[resolve(PROJECT_ROOT,".runs/v37/g3a-product/data/workflows",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/runs",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/regression",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a-product/assessments",created.workflow_id),resolve(PROJECT_ROOT,".runs/v37/g3a/state-stores/v37-det-recovery-promote-retain")],byteSnapshot=jsonInventory(roots);const registryPath=resolve(PROJECT_ROOT,"workbench/config/v37/g3a/registered-cases/registry-v1.json"),registryBytes=readFileSync(registryPath,"utf8"),registry=JSON.parse(registryBytes),entry=registry.entries.find((item:any)=>item.case_id==="v37-det-recovery-promote-retain");
	const disabledBody={schema_version:1,kind:"v37_case_registration_envelope",case_id:entry.case_id,manifest_version:entry.manifest_version,approved_manifest_body_digest:entry.manifest_body_digest,registration_revision:2,previous_registration_digest:entry.current_registration_digest,registration_status:"disabled",approval_record_id:"v37-g3a-main-registration-recovery-disabled-r2",approval_policy_id:"v37-main-reviewed-case-registration-v1",approved_at:"2026-08-20T17:00:00.000Z",disabled_at:"2026-08-20T17:00:01.000Z"};const disabled={...disabledBody,registration_digest:digestObject(disabledBody)},relative=".runs/v37/g3a-product/disabled/v37-det-recovery-r2.json",path=resolve(PROJECT_ROOT,relative);mkdirSync(resolve(path,".."),{recursive:true});writeFileSync(path,`${stableJson(disabled)}\n`);
	try{entry.envelope_locations.push(relative);entry.envelope_digests.push(disabled.registration_digest);entry.current_registration_digest=disabled.registration_digest;const {registry_index_digest:_old,...body}=registry;registry.registry_index_digest=digestObject(body);writeFileSync(registryPath,`${stableJson(registry)}\n`);const reopened=service().getWorkflow(created.workflow_id);assert.equal(reopened.stage,"complete");assert.equal(reopened.historical_read_only,true);assert.deepEqual(reopened.available_actions,[]);assert.deepEqual(reopened.artifacts,artifactSnapshot);assert.deepEqual(jsonInventory(roots),byteSnapshot);for(const action of actions)await assert.rejects(s.act(created.workflow_id,action),/read-only/);assert.deepEqual(jsonInventory(roots),byteSnapshot);}finally{writeFileSync(registryPath,registryBytes);rmSync(path,{force:true});}
});
