import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { cpSync, linkSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import type { ArtifactRefV0B, TaskSpecV0B } from "../src/contracts/v0b-types.ts";
import type { ActiveStateIdentityV3, HarnessStateVersionV3 } from "../src/contracts/v3g2-types.ts";
import type { BindingContextV3 } from "../src/contracts/v3g3-types.ts";
import type { FauxExecutionEventV3 } from "../src/contracts/v3g2-types.ts";
import type { ImprovementOpportunityV3, RefinementCandidateV3, StagedHarnessStateV3 } from "../src/contracts/v3-types.ts";
import { artifactRef, writeOnceBytes } from "../src/evidence/artifacts.ts";
import { digestObject, fileSha256, sha256, stableJson, treeDigest } from "../src/hash.ts";
import { inspectGoal3RunV3 } from "../src/inspect-v3.ts";
import { SYSTEM_PROMPT, SYSTEM_PROMPT_SHA256 } from "../src/prompts/base.ts";
import { admitCandidateV3, freezeAdmissionRegistryV3, inspectCandidateAdmissionV3 } from "../src/refinement/admission-v3.ts";
import { executeSymmetricValidationV3, type FauxValidationPortV3, type LocalCheckV3 } from "../src/refinement/comparator-v3.ts";
import { deterministicFixtureProposalV3, validateProposalAndBuildCandidateV3 } from "../src/refinement/producer-v3.ts";
import { executeGoal3RunV3 } from "../src/run-v3.ts";
import { createGoal3DeepSeekExecutionPortV3 } from "../src/pi/pi-adapter-v3.ts";
import { GOAL3_BUDGET_PROFILE_DIGEST_V3, GOAL3_BUDGET_PROFILE_V3, GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3, GOAL3_FAUX_PROVIDER_PROFILE_V3, goal3ToolProfileDigestV3 } from "../src/pi/runtime-profile-v3.ts";
import { createOneRunProviderAuthorityV1B } from "../src/provider/fixed-provider-v1.ts";
import { freezeRunBindingV3 } from "../src/state/binding-v3.ts";
import { buildBindingContextFromCaseAuthorityV3, freezeGoal3CaseAuthorityV3 } from "../src/state/case-authority-v3.ts";
import { stageCandidateStateV3 } from "../src/state/staging-v3.ts";
import { applyValidationDecisionV3, initializeStateStoreV3, inspectStateStoreV3, rollbackActiveStateV3 } from "../src/state/store-v3.ts";

const PROJECT_ROOT = resolve(import.meta.dirname, "../..");
const FIXTURE_ROOT = resolve(PROJECT_ROOT, "fixtures/v3");
const BASE_PATH = resolve(PROJECT_ROOT, "workbench/src/prompts/base.ts");
const SHARED_AUTHORITY = "D:/AI/AI_Projects/project2/.runs/v3-g3/shared-authority";
const TASK_PROMPT = "Inspect the bounded workspace, preserve protected files, and report completion without changing host authority.";
let authoritativeSequenceRoot: string | null = null;
let authoritativeAdmissionRegistryRoot: string | null = null;
const authorityPaths = new Map<string, string>();

function activeIdentity(value: { binding_revision: number; state_version: number; state_digest: string }): ActiveStateIdentityV3 {
	return { binding_revision: value.binding_revision, state_version: value.state_version, state_digest: value.state_digest };
}

function makeWorkspace(root: string, label: string, subject: "broken" | "fixed"): string {
	const workspace = resolve(root, label); mkdirSync(workspace, { recursive: true });
	writeFileSync(resolve(workspace, "subject.txt"), `${subject}\n`); writeFileSync(resolve(workspace, "protected.txt"), "protected-stable\n");
	return workspace;
}

function checkSource(root: string, verifierId: string, target: "subject" | "protected"): string {
	const path = resolve(root, `${verifierId}.mjs`); const expected = target === "subject" ? "fixed\n" : "protected-stable\n"; const file = target === "subject" ? "subject.txt" : "protected.txt";
	writeFileSync(path, `import { readFileSync } from "node:fs";\nimport { resolve } from "node:path";\nconst workspace = process.env.V0B_WORKSPACE;\nconst passed = typeof workspace === "string" && readFileSync(resolve(workspace, ${JSON.stringify(file)}), "utf8") === ${JSON.stringify(expected)};\nconsole.log(JSON.stringify({ schema_version: 1, verifier_id: ${JSON.stringify(verifierId)}, status: passed ? "passed" : "failed", summary: passed ? "passed" : "failed", ...(passed ? {} : { failed_checks: [${JSON.stringify(target)}] }) }));\nprocess.exit(passed ? 0 : 1);\n`);
	return path;
}

function taskSpec(workspace: string, verifierId: string, sourcePath: string): TaskSpecV0B {
	return { schema_version: 1, task_id: `v3g3-${verifierId}`, instruction_ref: "v3g3-frozen-instruction", instruction_sha256: sha256("execute bounded Goal 3 case"), workspace_source_ref: workspace, workspace_source_digest: treeDigest(workspace), writable_paths: ["subject.txt"], protected_paths: ["protected.txt"], verifier_id: verifierId, verifier_ref: sourcePath, verifier_sha256: fileSha256(sourcePath), acceptance_visibility: "hidden_external", tool_profile_id: "v3g3_bounded_local", command_descriptors: [], verifier_command: { executable: "current_node_executable", argv: [sourcePath], cwd: "project", timeout_ms: 5_000, output_limit_bytes: 8_192 } };
}

function localChecks(root: string, workspace: string): { verifier: LocalCheckV3; regressions: LocalCheckV3[] } {
	const verifierPath = checkSource(root, "v3g3-external-verifier", "subject"); const regressionPath = checkSource(root, "v3g3-prior-pass-regression", "protected");
	return { verifier: { task: taskSpec(workspace, "v3g3-external-verifier", verifierPath), sourcePath: verifierPath }, regressions: [{ task: taskSpec(workspace, "v3g3-prior-pass-regression", regressionPath), sourcePath: regressionPath }] };
}

function events(prefix: string, provider: number, tool: number, pathology: number): FauxExecutionEventV3[] {
	const result: FauxExecutionEventV3[] = [];
	for (let i = 0; i < provider; i++) result.push({ seq: result.length + 1, type: "provider_call", call_id: `${prefix}-provider-${i}` });
	for (let i = 0; i < tool; i++) result.push({ seq: result.length + 1, type: "tool_call", call_id: `${prefix}-tool-${i}` });
	for (let i = 0; i < pathology; i++) result.push({ seq: result.length + 1, type: "structural_pathology", check_id: `${prefix}-pathology-${i}` });
	return result;
}

const promotePort: FauxValidationPortV3 = { execute: async ({ state, workspaceRoot }) => { if (state.status === "staged_inactive") writeFileSync(resolve(workspaceRoot, "subject.txt"), "fixed\n"); return { settled: true, events: state.status === "accepted" ? events("base", 3, 3, 1) : events("candidate", 2, 2, 0) }; } };
const bothPassImprovePort: FauxValidationPortV3 = { execute: async ({ state }) => ({ settled: true, events: state.status === "accepted" ? events("base", 3, 3, 1) : events("candidate", 2, 2, 0) }) };
const bothFailPort: FauxValidationPortV3 = { execute: async ({ state }) => ({ settled: true, events: state.status === "accepted" ? events("base", 2, 2, 1) : events("candidate", 2, 2, 1) }) };

async function activeVersion(stateRoot: string, projectId: string): Promise<{ active: NonNullable<Awaited<ReturnType<typeof inspectStateStoreV3>>["active"]>; version: HarnessStateVersionV3 }> {
	const store = await inspectStateStoreV3({ stateRoot, expectedProjectId: projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 });
	assert.equal(store.integrity_valid, true, store.errors.join("; ")); assert.ok(store.active);
	const version = store.versions.find((entry) => entry.state_digest === store.active!.state_digest); assert.ok(version);
	return { active: store.active, version };
}

function opportunity(root: string, trigger: ImprovementOpportunityV3["trigger"], taskKind: string, failureFamily: string): ImprovementOpportunityV3 {
	const relative = `opportunity-${trigger}.txt`; writeOnceBytes(root, relative, `${trigger} frozen evidence\n`); const evidenceRef = artifactRef(root, relative, "text/plain", false); const evidenceDigest = sha256(`${trigger}-evidence`);
	return { schema_version: 1, opportunity_id: `opp-${trigger}`, trigger, source_run_ids: [`run-${trigger}`], evidence_identity: { evidence_id: `evidence-${trigger}`, evidence_digest: evidenceDigest }, evidence_refs: [evidenceRef], observations: { frozen: true }, derivation: "deterministic_projection", task_context: { task_kind: taskKind, failure_family: failureFamily } };
}

async function deterministicCandidate(options: { root: string; agentWorkspace: string; baseDigest: string; trigger: ImprovementOpportunityV3["trigger"]; kind: "prompt_addendum" | "adaptive_skill"; taskKind: string; failureFamily: string }): Promise<{ candidate: RefinementCandidateV3; stagedRoot: string; state: StagedHarnessStateV3 }> {
	const found = opportunity(options.root, options.trigger, options.taskKind, options.failureFamily); const proposal = deterministicFixtureProposalV3({ opportunity: found, currentBaseStateDigest: options.baseDigest, kind: options.kind }); const candidate = validateProposalAndBuildCandidateV3({ rawProposal: proposal, opportunity: found, currentBaseStateDigest: options.baseDigest, derivation: "deterministic_fixture" });
	const stagedRoot = resolve(options.root, `staged-${options.trigger}`); const staged = await stageCandidateStateV3({ candidate, stateRoot: stagedRoot, agentWorkspaceRoot: options.agentWorkspace, acceptedBaseRoots: [BASE_PATH], immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); return { candidate, stagedRoot, state: staged.state };
}

async function validateAndApply(options: { root: string; label: string; projectId: string; stateRoot: string; base: HarnessStateVersionV3; workspace: string; stagedRoot: string; candidateState: StagedHarnessStateV3; expectedActive: ActiveStateIdentityV3; port: FauxValidationPortV3 }) {
	const checks = localChecks(options.root, options.workspace); const runRoot = resolve(options.root, `validation-${options.label}`); const validation = await executeSymmetricValidationV3({ projectRoot: PROJECT_ROOT, runRoot, validationId: `v3g3-${options.label}`, projectId: options.projectId, sourceWorkspaceRoot: options.workspace, task: checks.verifier.task, verifier: checks.verifier, regressions: checks.regressions, baseState: options.base, candidateState: options.candidateState, providerModelProfileDigest: sha256("public-emitted-faux"), toolProfileDigest: sha256("v3g3-bounded-local"), budgetDigest: sha256("zero-real-bounded"), hardConstraintsDigest: sha256("authority-plane-frozen"), port: options.port });
	return await applyValidationDecisionV3({ stateRoot: options.stateRoot, projectId: options.projectId, runRoot, validationRef: validation.validationRef, stagedStateRoot: options.stagedRoot, candidateStateDigest: options.candidateState.state_digest, expectedActive: options.expectedActive, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 });
}

async function directRun(options: { root: string; label: string; stateRoot: string; admissionRegistryRoot: string; projectId: string; taskKind: string; failureFamily: string | null; workspace: string }) {
	const verifierPath = checkSource(options.root, `v3g3-run-verifier-${options.label}`, "protected"); const verifierTask = taskSpec(options.workspace, `v3g3-run-verifier-${options.label}`, verifierPath);
	const allowedFailureLineage = options.failureFamily === null ? null : { source_run_id: "trusted-prior-run", failure_family: options.failureFamily, lineage_digest: digestObject({ source_run_id: "trusted-prior-run", failure_family: options.failureFamily }) };
	const authority = freezeGoal3CaseAuthorityV3({ authorityRoot: resolve(options.root, "case-authorities"), projectId: options.projectId, taskId: verifierTask.task_id, caseId: options.label, taskKind: options.taskKind, allowedFailureLineage, taskPromptSha256: sha256(TASK_PROMPT), verifierId: verifierTask.verifier_id, verifierSha256: verifierTask.verifier_sha256, toolProfileId: verifierTask.tool_profile_id, toolProfileDigest: goal3ToolProfileDigestV3(verifierTask), budgetProfileId: GOAL3_BUDGET_PROFILE_V3.profile_id, budgetProfileDigest: GOAL3_BUDGET_PROFILE_DIGEST_V3, providerProfile: GOAL3_FAUX_PROVIDER_PROFILE_V3 });
	const context = buildBindingContextFromCaseAuthorityV3(authority.authority); const runRoot = resolve(options.root, `run-${options.label}`); mkdirSync(runRoot, { recursive: true }); authorityPaths.set(runRoot, authority.path);
	const frozen = await freezeRunBindingV3({ projectRoot: PROJECT_ROOT, stateRoot: options.stateRoot, admissionRegistryRoot: options.admissionRegistryRoot, caseAuthorityPath: authority.path, runRoot, projectId: options.projectId, context, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 });
	await executeGoal3RunV3({ projectRoot: PROJECT_ROOT, runRoot, runId: `v3g3-run-${options.label}`, caseId: options.label, caseAuthorityPath: authority.path, workspaceRoot: options.workspace, taskPrompt: TASK_PROMPT, taskPolicy: verifierTask, verifierTask, verifierSourcePath: verifierPath, frozen });
	const inspected = await inspectGoal3RunV3({ projectRoot: PROJECT_ROOT, stateRoot: options.stateRoot, admissionRegistryRoot: options.admissionRegistryRoot, caseAuthorityPath: authority.path, runRoot, expectedProjectId: options.projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); assert.equal(inspected.integrity_valid, true, inspected.errors.join("; "));
	return { runRoot, frozen, inspected, context, authorityPath: authority.path };
}

test("V3-G3 four frozen behavioral/regression Cases cover both State paths, all triggers, Reject, irrelevant binding, pointer drift, and rollback", async (t) => {
	const sequenceRoot = resolve(SHARED_AUTHORITY, `sequence-${randomUUID()}`); mkdirSync(sequenceRoot, { recursive: true }); const agentWorkspace = resolve(sequenceRoot, "agent-workspace"); mkdirSync(agentWorkspace); const stateRoot = resolve(sequenceRoot, "project-state"); const projectId = "v3-g3-portfolio-project";
	authoritativeSequenceRoot = sequenceRoot;
	const initialized = await initializeStateStoreV3({ stateRoot, projectId, agentWorkspaceRoot: agentWorkspace, acceptedBaseRoots: [BASE_PATH], immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); const version0 = initialized.version; const admissionRegistryRoot = resolve(sequenceRoot, "admission-authority"); authoritativeAdmissionRegistryRoot = admissionRegistryRoot;
	let promptVersion: HarnessStateVersionV3 | null = null; let case1RunRoot = ""; let case1BindingContext: BindingContextV3 | null = null; let skillVersion: HarnessStateVersionV3 | null = null;

	await t.test("Case 1 hard failure admits the real Goal 1 prompt Candidate, promotes it, and binds it in an independent subsequent Run", async () => {
		const root = resolve(sequenceRoot, "case-1"); mkdirSync(root); const sourceCandidate: RefinementCandidateV3 = JSON.parse(readFileSync(resolve(FIXTURE_ROOT, "goal1-real-candidate.json"), "utf8")); const sourceState: StagedHarnessStateV3 = JSON.parse(readFileSync(resolve(FIXTURE_ROOT, "goal1-real-staged-state.json"), "utf8")); const targetActive = activeIdentity(initialized.active); const admitted = admitCandidateV3({ admissionRoot: resolve(sequenceRoot, "admissions"), projectId, sourceCandidate, sourceState, targetActive }); const admissionInspection = inspectCandidateAdmissionV3({ admissionPath: admitted.path, expectedProjectId: projectId, sourceCandidate, sourceState, expectedCurrentActive: targetActive }); assert.equal(admissionInspection.integrity_valid, true, admissionInspection.errors.join("; ")); freezeAdmissionRegistryV3({ registryRoot: admissionRegistryRoot, projectRoot: PROJECT_ROOT, projectId, admissionPaths: [admitted.path] });
		const stagedRoot = resolve(root, "staged-admitted"); const staged = await stageCandidateStateV3({ candidate: admitted.admittedCandidate, stateRoot: stagedRoot, agentWorkspaceRoot: agentWorkspace, acceptedBaseRoots: [FIXTURE_ROOT], immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); const workspace = makeWorkspace(root, "validation-workspace", "broken"); const applied = await validateAndApply({ root, label: "case1-real-prompt", projectId, stateRoot, base: version0, workspace, stagedRoot, candidateState: staged.state, expectedActive: targetActive, port: promotePort }); assert.equal(applied.decision.result, "promoted"); assert.ok(applied.version); promptVersion = applied.version;
		const runWorkspace = makeWorkspace(root, "subsequent-workspace", "fixed"); const subsequent = await directRun({ root, label: "case1-relevant-prompt", stateRoot, admissionRegistryRoot, projectId, taskKind: "typescript-maintenance", failureFamily: "verifier-failure", workspace: runWorkspace }); assert.equal(subsequent.frozen.binding.bound_entries.length, 1); assert.equal(subsequent.frozen.binding.bound_entries[0]!.kind, "prompt_addendum"); assert.equal(subsequent.frozen.binding.lineage!.admission_digest, admitted.admission.admission_digest); case1RunRoot = subsequent.runRoot; case1BindingContext = subsequent.context;
	});

	await t.test("Case 2 inefficient success promotes deterministic adaptive Skill on a frozen prior-pass regression and uses public explicit Skill invocation", async () => {
		assert.ok(promptVersion); const root = resolve(sequenceRoot, "case-2"); mkdirSync(root); const current = await activeVersion(stateRoot, projectId); const candidate = await deterministicCandidate({ root, agentWorkspace, baseDigest: current.active.state_digest, trigger: "inefficient_success", kind: "adaptive_skill", taskKind: "typescript-maintenance", failureFamily: "prior-pass" }); const workspace = makeWorkspace(root, "validation-workspace", "fixed"); const applied = await validateAndApply({ root, label: "case2-skill", projectId, stateRoot, base: current.version, workspace, stagedRoot: candidate.stagedRoot, candidateState: candidate.state, expectedActive: activeIdentity(current.active), port: bothPassImprovePort }); assert.equal(applied.decision.reason, "both_passed_material_improvement"); assert.ok(applied.version); skillVersion = applied.version;
		const runWorkspace = makeWorkspace(root, "subsequent-workspace", "fixed"); const subsequent = await directRun({ root, label: "case2-relevant-skill-prior-pass", stateRoot, admissionRegistryRoot, projectId, taskKind: "typescript-maintenance", failureFamily: "prior-pass", workspace: runWorkspace }); assert.equal(subsequent.frozen.binding.adaptive_skill_name?.startsWith("adaptive-inefficient-success"), true); assert.equal(subsequent.frozen.binding.bound_entries[0]!.kind, "adaptive_skill"); assert.equal(subsequent.frozen.binding.lineage!.admission_digest, null);
	});

	await t.test("Case 3 structural repeated-failure Candidate is rejected when it does not improve and active pointer bytes remain identical", async () => {
		assert.ok(skillVersion); const root = resolve(sequenceRoot, "case-3"); mkdirSync(root); const current = await activeVersion(stateRoot, projectId); const candidate = await deterministicCandidate({ root, agentWorkspace, baseDigest: current.active.state_digest, trigger: "structural_trajectory_pathology", kind: "prompt_addendum", taskKind: "typescript-maintenance", failureFamily: "repeated-frozen-check" }); const workspace = makeWorkspace(root, "validation-workspace", "broken"); const before = readFileSync(resolve(stateRoot, "active.json")); const applied = await validateAndApply({ root, label: "case3-structural-reject", projectId, stateRoot, base: current.version, workspace, stagedRoot: candidate.stagedRoot, candidateState: candidate.state, expectedActive: activeIdentity(current.active), port: bothFailPort }); assert.equal(applied.decision.result, "rejected"); assert.equal(applied.decision.reason, "both_failed"); assert.deepEqual(readFileSync(resolve(stateRoot, "active.json")), before);
	});

	await t.test("Case 4 irrelevant task binds nothing, rollback retains history, and frozen prior Runs survive pointer drift", async () => {
		assert.ok(promptVersion && skillVersion && case1BindingContext); const root = resolve(sequenceRoot, "case-4"); mkdirSync(root); const current = await activeVersion(stateRoot, projectId); const irrelevantWorkspace = makeWorkspace(root, "irrelevant-workspace", "fixed"); const irrelevant = await directRun({ root, label: "case4-irrelevant", stateRoot, admissionRegistryRoot, projectId, taskKind: "documentation", failureFamily: null, workspace: irrelevantWorkspace }); assert.equal(irrelevant.frozen.binding.bound_entries.length, 0); assert.equal(irrelevant.frozen.binding.adaptive_skill_name, null);
		const rollback = await rollbackActiveStateV3({ stateRoot, projectId, targetStateDigest: promptVersion.state_digest, expectedActive: activeIdentity(current.active), immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); assert.equal(rollback.decision.result, "rolled_back"); assert.equal(rollback.active.state_digest, promptVersion.state_digest);
		const frozenBeforeRollback = await inspectGoal3RunV3({ projectRoot: PROJECT_ROOT, stateRoot, admissionRegistryRoot, caseAuthorityPath: irrelevant.authorityPath, runRoot: irrelevant.runRoot, expectedProjectId: projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); assert.equal(frozenBeforeRollback.integrity_valid, true, frozenBeforeRollback.errors.join("; ")); assert.equal(frozenBeforeRollback.pointer_drift_observed, true);
		const case1AfterDrift = await inspectGoal3RunV3({ projectRoot: PROJECT_ROOT, stateRoot, admissionRegistryRoot, caseAuthorityPath: authorityPaths.get(case1RunRoot)!, runRoot: case1RunRoot, expectedProjectId: projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); assert.equal(case1AfterDrift.integrity_valid, true, case1AfterDrift.errors.join("; ")); assert.equal(case1AfterDrift.pointer_drift_observed, true);
		const subsequentWorkspace = makeWorkspace(root, "rollback-subsequent-workspace", "fixed"); const subsequent = await directRun({ root, label: "case4-rollback-prior-version", stateRoot, admissionRegistryRoot, projectId, taskKind: "typescript-maintenance", failureFamily: "verifier-failure", workspace: subsequentWorkspace }); assert.equal(subsequent.frozen.binding.active_state_digest, promptVersion.state_digest); assert.equal(subsequent.frozen.binding.bound_entries[0]!.kind, "prompt_addendum"); const finalStore = await inspectStateStoreV3({ stateRoot, expectedProjectId: projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 }); assert.equal(finalStore.integrity_valid, true, finalStore.errors.join("; ")); assert.equal(finalStore.versions.length, 3); assert.equal(finalStore.decisions.filter((entry) => entry.kind === "promotion").length, 2); assert.equal(finalStore.decisions.filter((entry) => entry.kind === "rejection").length, 1); assert.equal(finalStore.decisions.filter((entry) => entry.kind === "rollback").length, 1);
	});
});

test("V3-G3 Inspector fails closed for coherent binding/runtime/Manifest tamper and ordinary-file path/link/hardlink violations", async () => {
	assert.ok(authoritativeSequenceRoot && authoritativeAdmissionRegistryRoot); const sourceRoot = authoritativeSequenceRoot; const admissionRegistryRoot = authoritativeAdmissionRegistryRoot; const stateRoot = resolve(sourceRoot, "project-state"); const projectId = "v3-g3-portfolio-project"; const sourceRun = resolve(sourceRoot, "case-4/run-case4-rollback-prior-version"); const sourceBinding = JSON.parse(readFileSync(resolve(sourceRun, "binding.json"), "utf8")); assert.ok(sourceBinding.lineage?.admission_digest); const sourceAuthorityPath = authorityPaths.get(sourceRun)!;
	const root = resolve(SHARED_AUTHORITY, `tamper-${randomUUID()}`); mkdirSync(root, { recursive: true });
	const inspect = async (runRoot: string, overrideStateRoot = stateRoot, overrideRegistryRoot = admissionRegistryRoot, overrideAuthorityPath = sourceAuthorityPath) => await inspectGoal3RunV3({ projectRoot: PROJECT_ROOT, stateRoot: overrideStateRoot, admissionRegistryRoot: overrideRegistryRoot, caseAuthorityPath: overrideAuthorityPath, runRoot, expectedProjectId: projectId, immutableBasePrompt: SYSTEM_PROMPT, immutableBasePromptSha256: SYSTEM_PROMPT_SHA256 });
	assert.equal((await inspect(sourceRun)).integrity_valid, true);
	assert.equal((await inspect(sourceRun, stateRoot, resolve(root, "omitted-registry"))).integrity_valid, false);

	const bindingRoot = resolve(root, "binding"); cpSync(sourceRun, bindingRoot, { recursive: true }); const bindingPath = resolve(bindingRoot, "binding.json"); const binding = JSON.parse(readFileSync(bindingPath, "utf8")); binding.binding_context.trusted_task_identity.task_kind = "forged-task"; const taskIdentity = binding.binding_context.trusted_task_identity; taskIdentity.identity_digest = digestObject({ task_id: taskIdentity.task_id, case_id: taskIdentity.case_id, task_kind: taskIdentity.task_kind }); binding.binding_context_digest = digestObject(binding.binding_context); const { binding_digest: _bindingDigest, ...bindingBody } = binding; binding.binding_digest = digestObject(bindingBody); writeFileSync(bindingPath, `${stableJson(binding)}\n`);
	const bindingRuntimePath = resolve(bindingRoot, "runtime.json"); const bindingRuntime = JSON.parse(readFileSync(bindingRuntimePath, "utf8")); bindingRuntime.binding_digest = binding.binding_digest; const { runtime_digest: _bindingRuntimeDigest, ...bindingRuntimeBody } = bindingRuntime; bindingRuntime.runtime_digest = digestObject(bindingRuntimeBody); writeFileSync(bindingRuntimePath, `${stableJson(bindingRuntime)}\n`);
	const bindingManifestPath = resolve(bindingRoot, "manifest.json"); const bindingManifest = JSON.parse(readFileSync(bindingManifestPath, "utf8")); bindingManifest.binding_digest = binding.binding_digest; bindingManifest.binding_ref_sha256 = fileSha256(bindingPath); const { manifest_digest: _bindingManifestDigest, ...bindingManifestBody } = bindingManifest; bindingManifest.manifest_digest = digestObject(bindingManifestBody); writeFileSync(bindingManifestPath, `${stableJson(bindingManifest)}\n`); assert.equal((await inspect(bindingRoot)).integrity_valid, false);

	const runtimeRoot = resolve(root, "runtime"); cpSync(sourceRun, runtimeRoot, { recursive: true }); const runtimePath = resolve(runtimeRoot, "runtime.json"); const runtime = JSON.parse(readFileSync(runtimePath, "utf8")); runtime.external_provider_calls = 1; const { runtime_digest: _runtimeDigest, ...runtimeBody } = runtime; runtime.runtime_digest = digestObject(runtimeBody); writeFileSync(runtimePath, `${stableJson(runtime)}\n`); assert.equal((await inspect(runtimeRoot)).integrity_valid, false);

	const manifestRoot = resolve(root, "manifest"); cpSync(sourceRun, manifestRoot, { recursive: true }); const manifestPath = resolve(manifestRoot, "manifest.json"); const manifest = JSON.parse(readFileSync(manifestPath, "utf8")); manifest.verifier_status = "failed"; const { manifest_digest: _manifestDigest, ...manifestBody } = manifest; manifest.manifest_digest = digestObject(manifestBody); writeFileSync(manifestPath, `${stableJson(manifest)}\n`); assert.equal((await inspect(manifestRoot)).integrity_valid, false);

	const inspectCoherentDeepSeekClaim = async (label: string, mutate: (runtime: Record<string, any>) => void) => {
		const sourceAuthority = JSON.parse(readFileSync(sourceAuthorityPath, "utf8"));
		const deepSeekAuthority = freezeGoal3CaseAuthorityV3({ authorityRoot: resolve(root, `${label}-authority`), projectId: sourceAuthority.project_id, taskId: sourceAuthority.task_id, caseId: sourceAuthority.case_id, taskKind: sourceAuthority.task_kind, allowedFailureLineage: sourceAuthority.allowed_failure_lineage, taskPromptSha256: sourceAuthority.task_prompt_sha256, verifierId: sourceAuthority.verifier_id, verifierSha256: sourceAuthority.verifier_sha256, toolProfileId: sourceAuthority.tool_profile_id, toolProfileDigest: sourceAuthority.tool_profile_digest, budgetProfileId: sourceAuthority.budget_profile_id, budgetProfileDigest: sourceAuthority.budget_profile_digest, providerProfile: GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3 });
		const runRoot = resolve(root, label); cpSync(sourceRun, runRoot, { recursive: true });
		const projectedBindingPath = resolve(runRoot, "binding.json"); const projectedBinding = JSON.parse(readFileSync(projectedBindingPath, "utf8")); projectedBinding.case_authority_digest = deepSeekAuthority.authority.authority_digest; const { binding_digest: _projectedBindingDigest, ...projectedBindingBody } = projectedBinding; projectedBinding.binding_digest = digestObject(projectedBindingBody); writeFileSync(projectedBindingPath, `${stableJson(projectedBinding)}\n`);
		const projectedRuntimePath = resolve(runRoot, "runtime.json"); const projectedRuntime = JSON.parse(readFileSync(projectedRuntimePath, "utf8")); Object.assign(projectedRuntime, { binding_digest: projectedBinding.binding_digest, case_authority_digest: deepSeekAuthority.authority.authority_digest, provider_kind: "deepseek_real", provider_id: GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3.provider_id, model_id: GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3.model_id, provider_profile_digest: GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3.profile_digest, dispatch_attempts: 1, provider_dispatches: 1, credential_reads: 1, network_calls: 1, external_provider_calls: 1, real_model_calls: 1, provider_requests: 1, input_tokens: 0, output_tokens: 0, cost_usd: 0, tool_calls: 0 }); mutate(projectedRuntime); const { runtime_digest: _projectedRuntimeDigest, ...projectedRuntimeBody } = projectedRuntime; projectedRuntime.runtime_digest = digestObject(projectedRuntimeBody); writeFileSync(projectedRuntimePath, `${stableJson(projectedRuntime)}\n`);
		const projectedManifestPath = resolve(runRoot, "manifest.json"); const projectedManifest = JSON.parse(readFileSync(projectedManifestPath, "utf8")); Object.assign(projectedManifest, { binding_ref_sha256: fileSha256(projectedBindingPath), binding_digest: projectedBinding.binding_digest, case_authority_digest: deepSeekAuthority.authority.authority_digest, provider_kind: projectedRuntime.provider_kind, provider_id: projectedRuntime.provider_id, model_id: projectedRuntime.model_id, provider_profile_digest: projectedRuntime.provider_profile_digest, dispatch_attempts: projectedRuntime.dispatch_attempts, provider_dispatches: projectedRuntime.provider_dispatches, credential_reads: projectedRuntime.credential_reads, network_calls: projectedRuntime.network_calls, external_provider_calls: projectedRuntime.external_provider_calls, real_model_calls: projectedRuntime.real_model_calls, provider_requests: projectedRuntime.provider_requests, input_tokens: projectedRuntime.input_tokens, output_tokens: projectedRuntime.output_tokens, cost_usd: projectedRuntime.cost_usd }); const { manifest_digest: _projectedManifestDigest, ...projectedManifestBody } = projectedManifest; projectedManifest.manifest_digest = digestObject(projectedManifestBody); writeFileSync(projectedManifestPath, `${stableJson(projectedManifest)}\n`);
		return await inspect(runRoot, stateRoot, admissionRegistryRoot, deepSeekAuthority.path);
	};
	assert.equal((await inspectCoherentDeepSeekClaim("deepseek-valid-accounting", () => {})).integrity_valid, true);
	assert.equal((await inspectCoherentDeepSeekClaim("deepseek-zero-access", (runtime) => { runtime.credential_reads = 0; runtime.network_calls = 0; runtime.external_provider_calls = 0; runtime.real_model_calls = 0; })).integrity_valid, false);
	assert.equal((await inspectCoherentDeepSeekClaim("deepseek-over-caps", (runtime) => { runtime.provider_requests = GOAL3_BUDGET_PROFILE_V3.provider_requests_max + 1; runtime.provider_dispatches = runtime.provider_requests; runtime.network_calls = runtime.provider_requests; runtime.external_provider_calls = runtime.provider_requests; runtime.real_model_calls = runtime.provider_requests; runtime.input_tokens = GOAL3_BUDGET_PROFILE_V3.token_limit + 1; runtime.cost_usd = GOAL3_BUDGET_PROFILE_V3.cost_usd_max + 0.01; runtime.tool_calls = GOAL3_BUDGET_PROFILE_V3.tool_calls_max + 1; })).integrity_valid, false);

	const arbitraryRegistryRoot = resolve(root, "arbitrary-registry"); cpSync(admissionRegistryRoot, arbitraryRegistryRoot, { recursive: true }); const arbitraryRegistryPath = resolve(arbitraryRegistryRoot, "registry.json"); const arbitraryRegistry = JSON.parse(readFileSync(arbitraryRegistryPath, "utf8")); arbitraryRegistry.entries[0].admission_digest = "0".repeat(64); const { registry_digest: _arbitraryRegistryDigest, ...arbitraryRegistryBody } = arbitraryRegistry; arbitraryRegistry.registry_digest = digestObject(arbitraryRegistryBody); writeFileSync(arbitraryRegistryPath, `${stableJson(arbitraryRegistry)}\n`); assert.equal((await inspect(sourceRun, stateRoot, arbitraryRegistryRoot)).integrity_valid, false);
	const swappedRegistryRoot = resolve(root, "swapped-registry"); cpSync(admissionRegistryRoot, swappedRegistryRoot, { recursive: true }); const swappedRegistryPath = resolve(swappedRegistryRoot, "registry.json"); const swappedRegistry = JSON.parse(readFileSync(swappedRegistryPath, "utf8")); const originalAdmissionPath = resolve(swappedRegistryRoot, swappedRegistry.entries[0].admission_ref); const swappedAdmissionPath = resolve(swappedRegistryRoot, "admissions/swapped.json"); const swappedAdmission = JSON.parse(readFileSync(originalAdmissionPath, "utf8")); swappedAdmission.original_candidate_digest = "1".repeat(64); const { admission_digest: _swappedAdmissionDigest, ...swappedAdmissionBody } = swappedAdmission; swappedAdmission.admission_digest = digestObject(swappedAdmissionBody); writeFileSync(swappedAdmissionPath, `${stableJson(swappedAdmission)}\n`); swappedRegistry.entries[0].admission_ref = "admissions/swapped.json"; swappedRegistry.entries[0].admission_digest = swappedAdmission.admission_digest; swappedRegistry.entries[0].admission_file_sha256 = fileSha256(swappedAdmissionPath); const { registry_digest: _swappedRegistryDigest, ...swappedRegistryBody } = swappedRegistry; swappedRegistry.registry_digest = digestObject(swappedRegistryBody); writeFileSync(swappedRegistryPath, `${stableJson(swappedRegistry)}\n`); assert.equal((await inspect(sourceRun, stateRoot, swappedRegistryRoot)).integrity_valid, false);

	const staleRegistryRoot = resolve(root, "stale-registry"); cpSync(admissionRegistryRoot, staleRegistryRoot, { recursive: true }); const staleRegistryPath = resolve(staleRegistryRoot, "registry.json"); const staleRegistry = JSON.parse(readFileSync(staleRegistryPath, "utf8")); const staleAdmissionPath = resolve(staleRegistryRoot, staleRegistry.entries[0].admission_ref); const staleAdmission = JSON.parse(readFileSync(staleAdmissionPath, "utf8")); staleAdmission.target_active.binding_revision += 1; const { admission_digest: _staleAdmissionDigest, ...staleAdmissionBody } = staleAdmission; staleAdmission.admission_digest = digestObject(staleAdmissionBody); writeFileSync(staleAdmissionPath, `${stableJson(staleAdmission)}\n`); staleRegistry.entries[0].admission_digest = staleAdmission.admission_digest; staleRegistry.entries[0].admission_file_sha256 = fileSha256(staleAdmissionPath); const { registry_digest: _staleRegistryDigest, ...staleRegistryBody } = staleRegistry; staleRegistry.registry_digest = digestObject(staleRegistryBody); writeFileSync(staleRegistryPath, `${stableJson(staleRegistry)}\n`);
	const staleRun = resolve(root, "stale-run"); cpSync(sourceRun, staleRun, { recursive: true }); const staleBindingPath = resolve(staleRun, "binding.json"); const staleBinding = JSON.parse(readFileSync(staleBindingPath, "utf8")); staleBinding.lineage.admission_digest = staleAdmission.admission_digest; const { binding_digest: _staleBindingDigest, ...staleBindingBody } = staleBinding; staleBinding.binding_digest = digestObject(staleBindingBody); writeFileSync(staleBindingPath, `${stableJson(staleBinding)}\n`); const staleRuntimePath = resolve(staleRun, "runtime.json"); const staleRuntime = JSON.parse(readFileSync(staleRuntimePath, "utf8")); staleRuntime.binding_digest = staleBinding.binding_digest; const { runtime_digest: _staleRuntimeDigest, ...staleRuntimeBody } = staleRuntime; staleRuntime.runtime_digest = digestObject(staleRuntimeBody); writeFileSync(staleRuntimePath, `${stableJson(staleRuntime)}\n`); const staleManifestPath = resolve(staleRun, "manifest.json"); const staleManifest = JSON.parse(readFileSync(staleManifestPath, "utf8")); staleManifest.binding_digest = staleBinding.binding_digest; staleManifest.binding_ref_sha256 = fileSha256(staleBindingPath); const { manifest_digest: _staleManifestDigest, ...staleManifestBody } = staleManifest; staleManifest.manifest_digest = digestObject(staleManifestBody); writeFileSync(staleManifestPath, `${stableJson(staleManifest)}\n`); assert.equal((await inspect(staleRun, stateRoot, staleRegistryRoot)).integrity_valid, false);

	const hardlinkRoot = resolve(root, "hardlink"); cpSync(sourceRun, hardlinkRoot, { recursive: true }); linkSync(resolve(hardlinkRoot, "binding.json"), resolve(hardlinkRoot, "binding-copy.json")); assert.equal((await inspect(hardlinkRoot)).integrity_valid, false);
	const authorityHardlinkRoot = resolve(root, "authority-hardlink"); mkdirSync(authorityHardlinkRoot); const authorityHardlinkPath = resolve(authorityHardlinkRoot, "authority.json"); cpSync(sourceAuthorityPath, authorityHardlinkPath); linkSync(authorityHardlinkPath, resolve(authorityHardlinkRoot, "authority-copy.json")); assert.equal((await inspect(sourceRun, stateRoot, admissionRegistryRoot, authorityHardlinkPath)).integrity_valid, false);
	const registryHardlinkRoot = resolve(root, "registry-hardlink"); cpSync(admissionRegistryRoot, registryHardlinkRoot, { recursive: true }); linkSync(resolve(registryHardlinkRoot, "registry.json"), resolve(registryHardlinkRoot, "registry-copy.json")); assert.equal((await inspect(sourceRun, stateRoot, registryHardlinkRoot)).integrity_valid, false);

	const junction = resolve(root, "state-junction"); symlinkSync(stateRoot, junction, "junction"); assert.equal((await inspect(sourceRun, junction)).integrity_valid, false);
});

test("V3-G3 fixed DeepSeek execution port composes before dispatch with zero credential, network, Provider, or model access", async () => {
	const frozen = freezeGoal3CaseAuthorityV3({ authorityRoot: resolve(PROJECT_ROOT, `.runs/v3-g3/real-port-preflight/${randomUUID()}`), projectId: "v3-g3-real-preflight", taskId: "v3-g3-real-task", caseId: "real-preflight", taskKind: "typescript-maintenance", allowedFailureLineage: null, taskPromptSha256: sha256(TASK_PROMPT), verifierId: "v3-g3-real-verifier", verifierSha256: sha256("frozen-real-verifier"), toolProfileId: "v3g3_bounded_local", toolProfileDigest: goal3ToolProfileDigestV3({ writable_paths: [], protected_paths: [], command_descriptors: [] }), budgetProfileId: GOAL3_BUDGET_PROFILE_V3.profile_id, budgetProfileDigest: GOAL3_BUDGET_PROFILE_DIGEST_V3, providerProfile: GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3 });
	const counters = { credential_reads: 0, network_calls: 0, external_provider_calls: 0, real_model_calls: 0 };
	let injectedResolverCalls = 0;
	const authority = createOneRunProviderAuthorityV1B({ authorized: true, resolver: { resolve: async () => { injectedResolverCalls++; return "must-not-be-read-during-composition"; } } });
	const port = createGoal3DeepSeekExecutionPortV3({ authority, counters });
	assert.deepEqual(port.profile, GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3);
	assert.equal(frozen.authority.provider_profile.profile_digest, port.profile.profile_digest);
	assert.deepEqual(counters, { credential_reads: 0, network_calls: 0, external_provider_calls: 0, real_model_calls: 0 });
	assert.equal(injectedResolverCalls, 0);
	await port.close();
	assert.deepEqual(counters, { credential_reads: 0, network_calls: 0, external_provider_calls: 0, real_model_calls: 0 });
});
