import { existsSync, lstatSync, readFileSync, realpathSync } from "node:fs";
import { isAbsolute, relative, resolve, sep } from "node:path";
import { JsonlSessionRepo } from "@earendil-works/pi-agent-core";
import { NodeExecutionEnv } from "@earendil-works/pi-agent-core/node";
import type { VerifierResultV0B } from "../contracts/v0b-types.ts";
import type { DirectPiRuntimeEvidenceV3, FrozenRunBindingV3, Goal3RunManifestV3 } from "../contracts/v3g3-types.ts";
import type { Goal2ArmManifestV35, Goal2ArmV35, Goal2ComparisonV35, Goal2SessionRecordV35 } from "../contracts/v35g2-types.ts";
import { artifactRef, readJsonArtifact, resolveRunRelative, validateArtifactRef } from "../evidence/artifacts.ts";
import { digestObject, stableJson } from "../hash.ts";
import { SYSTEM_PROMPT_SHA256 } from "../prompts/base.ts";
import { GOAL3_BUDGET_PROFILE_V3, GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3 } from "../pi/runtime-profile-v3.ts";
import { GOAL2_BASE_RUN_ID_V35, GOAL2_BASE_SESSION_ID_V35, GOAL2_CANDIDATE_RUN_ID_V35, GOAL2_CANDIDATE_SESSION_ID_V35, GOAL2_CASE_AUTHORITY_DIGEST_V35, GOAL2_CASE_ID_V35, GOAL2_COMPARISON_ID_V35, GOAL2_EFFECTIVE_TOOL_SURFACE_DIGEST_V35, GOAL2_PROJECT_ID_V35, GOAL2_SELECTED_STATE_DIGEST_V35, GOAL2_SKILL_NAME_V35, GOAL2_SKILL_SOURCE_SHA256_V35, GOAL2_SKILL_WRAPPER_SHA256_V35, GOAL2_WORKSPACE_DIGEST_V35 } from "./case-v35g2.ts";
import { inspectGoal2StateSelectionV35 } from "./state-selection-v35g2.ts";

function safeRoot(path: string): string {
	const stats = lstatSync(path); if (!stats.isDirectory() || stats.isSymbolicLink()) throw new Error("Goal 2 pair root is invalid");
	return realpathSync.native(resolve(path));
}
function contained(root: string, target: string): boolean { const rel = relative(root, target); return rel === "" || (!isAbsolute(rel) && rel !== ".." && !rel.startsWith(`..${sep}`)); }
function ordinaryJson<T>(path: string): T { const stats = lstatSync(path); if (!stats.isFile() || stats.isSymbolicLink() || stats.nlink !== 1) throw new Error("Goal 2 evidence must be an ordinary file"); return JSON.parse(readFileSync(path, "utf8")) as T; }
function body(value: Record<string, unknown>, key: string): Record<string, unknown> { const copy = { ...value }; delete copy[key]; return copy; }
function validDigest(value: Record<string, unknown>, key: string): boolean { return typeof value[key] === "string" && value[key] === digestObject(body(value, key)); }
function exactKeys(value: object, expected: readonly string[], label: string): void { if (stableJson(Object.keys(value).sort()) !== stableJson([...expected].sort())) throw new Error(`${label} exact-key validation failed`); }
function dominates(left: Goal2ArmManifestV35, right: Goal2ArmManifestV35): boolean { const a = [left.provider_requests, left.tool_calls, left.tokens, left.cost_usd, left.elapsed_ms, left.semantic_diff_lines]; const b = [right.provider_requests, right.tool_calls, right.tokens, right.cost_usd, right.elapsed_ms, right.semantic_diff_lines]; return a.every((value, index) => value <= b[index]!) && a.some((value, index) => value < b[index]!); }

async function inspectArm(pairRoot: string, comparison: Goal2ComparisonV35, arm: Goal2ArmV35): Promise<{ manifest: Goal2ArmManifestV35; runtime: DirectPiRuntimeEvidenceV3; binding: FrozenRunBindingV3 }> {
	const expected = arm === "base" ? { run: GOAL2_BASE_RUN_ID_V35, session: GOAL2_BASE_SESSION_ID_V35, ref: comparison.base_manifest_ref } : { run: GOAL2_CANDIDATE_RUN_ID_V35, session: GOAL2_CANDIDATE_SESSION_ID_V35, ref: comparison.candidate_manifest_ref };
	if (validateArtifactRef(pairRoot, expected.ref).length !== 0) throw new Error(`${arm} Goal 2 Manifest reference invalid`);
	const manifestPath = resolveRunRelative(pairRoot, expected.ref.path);
	const runRoot = resolve(manifestPath, "..");
	const manifest = ordinaryJson<Goal2ArmManifestV35>(manifestPath);
	exactKeys(manifest, ["schema_version", "project_id", "case_id", "arm", "run_id", "session_id", "workspace_id", "initial_workspace_digest", "final_workspace_digest", "protected_before_digest", "protected_after_digest", "task_prompt_sha256", "state_selection_digest", "binding_digest", "case_authority_digest", "effective_tool_surface_digest", "v3_manifest_ref", "binding_ref", "final_subject_ref", "runtime_ref", "verifier_ref", "session_record_ref", "verifier_status", "external_verifier_runs", "provider_requests", "tool_calls", "tokens", "cost_usd", "elapsed_ms", "semantic_diff_lines", "manifest_digest"], `${arm} Goal 2 Manifest`);
	if (!validDigest(manifest as unknown as Record<string, unknown>, "manifest_digest") || manifest.schema_version !== 1 || manifest.project_id !== GOAL2_PROJECT_ID_V35 || manifest.case_id !== GOAL2_CASE_ID_V35 || manifest.arm !== arm || manifest.run_id !== expected.run || manifest.session_id !== expected.session || manifest.initial_workspace_digest !== GOAL2_WORKSPACE_DIGEST_V35 || manifest.protected_before_digest !== manifest.protected_after_digest || manifest.case_authority_digest !== comparison.case_authority_digest || manifest.state_selection_digest !== comparison.state_selection_digest || manifest.effective_tool_surface_digest !== GOAL2_EFFECTIVE_TOOL_SURFACE_DIGEST_V35 || manifest.external_verifier_runs !== 1) throw new Error(`${arm} Goal 2 Manifest identity invalid`);
	for (const ref of [manifest.v3_manifest_ref, manifest.binding_ref, manifest.final_subject_ref, manifest.runtime_ref, manifest.verifier_ref, manifest.session_record_ref]) if (validateArtifactRef(runRoot, ref).length !== 0) throw new Error(`${arm} linked artifact invalid`);
	const v3Manifest = readJsonArtifact<Goal3RunManifestV3>(runRoot, manifest.v3_manifest_ref.path);
	const runtime = readJsonArtifact<DirectPiRuntimeEvidenceV3>(runRoot, manifest.runtime_ref.path);
	const binding = readJsonArtifact<FrozenRunBindingV3>(runRoot, manifest.binding_ref.path);
	const verifier = readJsonArtifact<VerifierResultV0B>(runRoot, manifest.verifier_ref.path);
	const sessionRecord = readJsonArtifact<Goal2SessionRecordV35>(runRoot, manifest.session_record_ref.path);
	exactKeys(v3Manifest, ["schema_version", "run_id", "case_id", "task_id", "task_prompt_sha256", "binding_ref_sha256", "binding_digest", "case_authority_digest", "runtime_path", "provider_kind", "provider_id", "model_id", "provider_profile_digest", "dispatch_attempts", "provider_dispatches", "credential_reads", "network_calls", "external_provider_calls", "real_model_calls", "provider_requests", "input_tokens", "output_tokens", "cost_usd", "verifier_status", "manifest_digest"], `${arm} V3 Manifest`);
	exactKeys(runtime, ["schema_version", "run_id", "binding_digest", "case_authority_digest", "runtime_path", "session_id", "settled_events", "provider_kind", "provider_id", "model_id", "provider_profile_digest", "dispatch_attempts", "provider_dispatches", "credential_reads", "network_calls", "external_provider_calls", "real_model_calls", "provider_requests", "input_tokens", "output_tokens", "cost_usd", "tool_calls", "tool_profile_digest", "task_prompt_sha256", "observed_system_prompt_sha256", "observed_user_message_sha256", "observed_skill_wrapper_sha256", "model_payload_sha256", "runtime_digest"], `${arm} runtime`);
	exactKeys(binding, ["schema_version", "project_id", "active_binding_revision", "active_state_version", "active_state_digest", "active_decision_id", "case_authority_digest", "binding_context", "binding_context_digest", "bound_entries", "composed_prompt_sha256", "adaptive_skill_name", "adaptive_skill_source_sha256", "adaptive_skill_wrapper_sha256", "lineage", "binding_digest"], `${arm} binding`);
	exactKeys(sessionRecord, ["schema_version", "project_id", "arm", "session_id", "session_ref", "workspace_id", "run_id", "run_ref", "created_at", "session_entry_count_after_run", "session_entries_sha256_after_run", "record_digest"], `${arm} Session record`);
	if (!validDigest(v3Manifest as unknown as Record<string, unknown>, "manifest_digest") || !validDigest(runtime as unknown as Record<string, unknown>, "runtime_digest") || !validDigest(binding as unknown as Record<string, unknown>, "binding_digest") || !validDigest(sessionRecord as unknown as Record<string, unknown>, "record_digest")) throw new Error(`${arm} linked digest invalid`);
	if (v3Manifest.run_id !== expected.run || runtime.run_id !== expected.run || runtime.session_id !== expected.session || sessionRecord.project_id !== GOAL2_PROJECT_ID_V35 || sessionRecord.run_id !== expected.run || sessionRecord.session_id !== expected.session || sessionRecord.arm !== arm || sessionRecord.workspace_id !== manifest.workspace_id || sessionRecord.run_ref !== relative(pairRoot, manifestPath).split(sep).join("/") || v3Manifest.binding_digest !== binding.binding_digest || runtime.binding_digest !== binding.binding_digest || manifest.binding_digest !== binding.binding_digest || v3Manifest.case_authority_digest !== comparison.case_authority_digest || runtime.case_authority_digest !== comparison.case_authority_digest || verifier.status !== manifest.verifier_status || v3Manifest.verifier_status !== manifest.verifier_status || runtime.task_prompt_sha256 !== manifest.task_prompt_sha256) throw new Error(`${arm} Run/Session/binding/Verifier lineage invalid`);
	if (manifest.provider_requests !== runtime.provider_requests || manifest.tool_calls !== runtime.tool_calls || manifest.tokens !== runtime.input_tokens + runtime.output_tokens || manifest.cost_usd !== runtime.cost_usd || runtime.dispatch_attempts !== 1 || runtime.settled_events !== 1 || runtime.provider_dispatches !== runtime.provider_requests || runtime.provider_requests < 1 || runtime.provider_requests > GOAL3_BUDGET_PROFILE_V3.provider_requests_max || runtime.tool_calls > GOAL3_BUDGET_PROFILE_V3.tool_calls_max || manifest.tokens > GOAL3_BUDGET_PROFILE_V3.token_limit || runtime.cost_usd > GOAL3_BUDGET_PROFILE_V3.cost_usd_max) throw new Error(`${arm} usage/budget evidence invalid`);
	if (runtime.provider_kind !== "deepseek_real" || runtime.provider_profile_digest !== GOAL3_DEEPSEEK_PROVIDER_PROFILE_V3.profile_digest || runtime.credential_reads !== 1 || runtime.network_calls !== runtime.provider_requests || runtime.external_provider_calls !== runtime.provider_requests || runtime.real_model_calls !== runtime.provider_requests) throw new Error(`${arm} frozen real Provider accounting invalid`);
	if (binding.project_id !== GOAL2_PROJECT_ID_V35 || binding.active_state_version !== 2 || binding.active_state_digest !== GOAL2_SELECTED_STATE_DIGEST_V35 || binding.composed_prompt_sha256 !== SYSTEM_PROMPT_SHA256 || binding.case_authority_digest !== comparison.case_authority_digest || runtime.observed_system_prompt_sha256 !== SYSTEM_PROMPT_SHA256) throw new Error(`${arm} State/System binding invalid`);
	if (arm === "base" ? binding.bound_entries.length !== 0 || binding.adaptive_skill_name !== null || runtime.observed_skill_wrapper_sha256 !== null || runtime.runtime_path !== "unbound_prompt" : binding.bound_entries.length !== 1 || binding.adaptive_skill_name !== GOAL2_SKILL_NAME_V35 || binding.adaptive_skill_source_sha256 !== GOAL2_SKILL_SOURCE_SHA256_V35 || binding.adaptive_skill_wrapper_sha256 !== GOAL2_SKILL_WRAPPER_SHA256_V35 || runtime.observed_skill_wrapper_sha256 !== GOAL2_SKILL_WRAPPER_SHA256_V35 || runtime.runtime_path !== "adaptive_skill") throw new Error(`${arm} treatment boundary invalid`);
	const sessionPath = resolve(pairRoot, sessionRecord.session_ref);
	if (!contained(pairRoot, sessionPath) || !existsSync(sessionPath)) throw new Error(`${arm} persistent Session reference invalid`);
	const repo = new JsonlSessionRepo({ fs: new NodeExecutionEnv({ cwd: pairRoot, shellEnv: {} }), sessionsRoot: resolve(pairRoot, "sessions") });
	const metadata = (await repo.list()).find((entry) => entry.id === expected.session);
	const expectedWorkspace = realpathSync.native(resolve(pairRoot, "workspaces", arm)); const custom = metadata?.metadata as Record<string, unknown> | undefined;
	if (!metadata || realpathSync.native(resolve(metadata.path)) !== realpathSync.native(sessionPath) || realpathSync.native(resolve(metadata.cwd)) !== expectedWorkspace || custom?.project_id !== GOAL2_PROJECT_ID_V35 || custom.workspace_id !== manifest.workspace_id || custom.arm !== arm) throw new Error(`${arm} persistent Session discovery invalid`);
	const session = await repo.open(metadata); const entries = await session.getEntries();
	if (entries.length < sessionRecord.session_entry_count_after_run || digestObject(entries.slice(0, sessionRecord.session_entry_count_after_run)) !== sessionRecord.session_entries_sha256_after_run) throw new Error(`${arm} persistent Session historical prefix invalid`);
	const verifierSource = artifactRef(runRoot, "verifier/source.mjs", "text/javascript; charset=utf-8", false);
	if (verifierSource.sha256 !== "470e9a49f27ebf3a14bd8d104f4e0a4a0e62a018e649352e56bfc418fa2a2fef") throw new Error(`${arm} hidden Verifier source drift`);
	return { manifest, runtime, binding };
}

export async function inspectGoal2PairV35(options: { pairRoot: string }): Promise<{ integrity_valid: boolean; errors: string[]; comparison: Goal2ComparisonV35 | null; base: Goal2ArmManifestV35 | null; candidate: Goal2ArmManifestV35 | null }> {
	const errors: string[] = []; let comparison: Goal2ComparisonV35 | null = null; let base: Goal2ArmManifestV35 | null = null; let candidate: Goal2ArmManifestV35 | null = null;
	try {
		const pairRoot = safeRoot(options.pairRoot);
		comparison = ordinaryJson<Goal2ComparisonV35>(resolve(pairRoot, "comparison.json"));
		exactKeys(comparison, ["schema_version", "comparison_id", "project_id", "case_id", "arm_order", "base_run_id", "candidate_run_id", "base_manifest_ref", "candidate_manifest_ref", "state_selection_digest", "case_authority_digest", "fairness_valid", "result", "efficiency", "comparison_digest"], "Goal 2 comparison");
		if (!validDigest(comparison as unknown as Record<string, unknown>, "comparison_digest") || comparison.schema_version !== 1 || comparison.comparison_id !== GOAL2_COMPARISON_ID_V35 || comparison.project_id !== GOAL2_PROJECT_ID_V35 || comparison.case_id !== GOAL2_CASE_ID_V35 || stableJson(comparison.arm_order) !== stableJson(["base", "candidate"]) || comparison.base_run_id !== GOAL2_BASE_RUN_ID_V35 || comparison.candidate_run_id !== GOAL2_CANDIDATE_RUN_ID_V35 || comparison.case_authority_digest !== GOAL2_CASE_AUTHORITY_DIGEST_V35 || comparison.fairness_valid !== true) throw new Error("Goal 2 comparison identity invalid");
		const selection = await inspectGoal2StateSelectionV35({ authorityRoot: resolve(pairRoot, "authority/state-selection") });
		if (comparison.state_selection_digest !== selection.authority.authority_digest) throw new Error("Goal 2 comparison/State selection mismatch");
		const inspectedBase = await inspectArm(pairRoot, comparison, "base"); const inspectedCandidate = await inspectArm(pairRoot, comparison, "candidate"); base = inspectedBase.manifest; candidate = inspectedCandidate.manifest;
		if (stableJson(inspectedBase.binding.binding_context) !== stableJson(inspectedCandidate.binding.binding_context) || stableJson(inspectedBase.binding.lineage) !== stableJson(inspectedCandidate.binding.lineage) || base.initial_workspace_digest !== candidate.initial_workspace_digest || base.task_prompt_sha256 !== candidate.task_prompt_sha256 || base.case_authority_digest !== candidate.case_authority_digest || base.state_selection_digest !== candidate.state_selection_digest) throw new Error("Goal 2 arm fairness recomputation failed");
		const expectedResult = base.verifier_status === "failed" && candidate.verifier_status === "passed" ? "positive_skill_effect" : base.verifier_status === "passed" && candidate.verifier_status === "failed" ? "negative_skill_effect" : base.verifier_status === "passed" ? "both_passed" : "both_failed";
		const expectedEfficiency = expectedResult !== "both_passed" ? "not_applicable" : dominates(base, candidate) ? "base_efficiency_dominant" : dominates(candidate, base) ? "candidate_efficiency_dominant" : "mixed_or_no_material_difference";
		if (comparison.result !== expectedResult || comparison.efficiency !== expectedEfficiency || base.cost_usd + candidate.cost_usd > 0.40 || inspectedBase.runtime.credential_reads + inspectedCandidate.runtime.credential_reads > 2 || inspectedBase.runtime.real_model_calls + inspectedCandidate.runtime.real_model_calls > 32) throw new Error("Goal 2 comparison result or pair budget invalid");
	} catch (error) { errors.push(error instanceof Error ? error.message : String(error)); }
	return { integrity_valid: errors.length === 0, errors, comparison, base, candidate };
}
